### ISSUE TITLE
تغییر نسخه play-services-ads

### ISSUE THREAD

**Issue by farzadnone** [tapsellorg/TapsellPlusSDK-AndroidSample#11]
سلام. من میخام از نسخه جدید:

`com.google.android.gms:play-services-ads:18.3.0`

استفاده کنم. نسخه ای که شما قرار دادید این 17.2.1 است.

چه باید کرد؟ مشکلی پیش میاد؟ چرا بروز نمی کنید اینارو؟

**Comment by tapselladnet** [comment]
سلام
مشکلی نیست
اپدیت کنید
