### ISSUE TITLE
File not found: applovin-sdk-6.3.0.jar

### ISSUE THREAD

**Issue by farzadnone** [tapsellorg/TapsellPlusSDK-AndroidSample#12]
salam. moghe gradle in error mide:

`File not found: C:\Users\ALFA\AndroidStudioProjects\MyProjects\app\libs\applovin-sdk-6.3.0.jar`

version tapsell:

`implementation 'ir.tapsell.plus:tapsell-plus-sdk-android:1.0.12'`

**Comment by behdad222** [comment]
سلام
این ارور به تپسل ارتباط ندارد
تنظیمات گردل رو انجام دادید
پیشنهاد میدم خطی که برای اضافه کردن aar اپلاوین اضافه کردید رو پاک کنید
و مطابق چیزی که تومستندات نوشته شده اضافه کنید

**Comment by shadowalker77** [comment]
سلام.
من هم این ارور رو دارم در حالی که کلا از اپلاوین استفاده نکردم. این ارور هم فقط وقتی پروگارد فعال باشه داده میشه با این که من تنظیمات پروگارد رو هم اد کردم.

**Comment by sadrash** [comment]
@behdad222 متاسفانه من هم همین مشکل رو در فلاتر دارم تو حالت دیباگ مشکلی نیست اما موقع بیلد به همین پکیج گیر میده تو پروگارد. لطفا بررسی نمایید بخش فلاتر رو یا یک فردی که تو تپسل کار می کنه رو این بخش رو ایمیلش رو در اختیارم قرار بدید.

**Comment by behdad222** [comment]
@sadrash همکاری کم با تپسل تموم شده
بچه‌های جدید میتونند کمکتون کنند

**Comment by sadrash** [comment]
@behdad222 هیچ کدوم جوابگو نیستن بی زحمت ایمیلی یا راه ارتباطی رو معرفی می کنید ؟

**Comment by behdad222** [comment]
@sadrash از قسمت پشتیبانی سایت بپرسید

**Comment by mahyari** [comment]
I'd same problem, I commented below line in proguard file and problem solved.

```
-libraryjars libs/applovin-sdk-6.3.0.jar
```

**Comment by behrooz-fard** [comment]
Now you can use Applovin by adding this line to your build.gradle file:

`implementation 'com.applovin:applovin-sdk:9.15.3'`
