### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by FirstVoyager** [tapsellorg/TapsellPlusSDK-AndroidSample#14]
File not found: /home/milad/File/projects/Project/app/libs/applovin-sdk-6.3.0.jar

اینو دقیقا چطوری باید رفع کرد؟

**Comment by behrooz-fard** [comment]
سلام
بابت تاخیر در پاسخ‌گویی صمیمانه عذرخواهی می‌کنم. آیا هنوز این مشکل را دارید؟
@FirstVoyager

**Comment by FirstVoyager** [comment]
خواهش می کنم.
من شغلم رو عوض کردم 😅
