### ISSUE TITLE
مشکل در زمان بیلد اندروید با فلاتر

### ISSUE THREAD

**Issue by sadrash** [tapsellorg/TapsellPlusSDK-AndroidSample#15]
با وجود اضافه کردن applovin-sdk-6.3.0.jar به پروژه در فلاتر در فایل پروگارد در زمان بیلد به خط ذیل گیر میده.
-libraryjars libs/applovin-sdk-6.3.0.jar
لطفا بررسی نمایید. ۱۰ روز هست که در بخش فلاتر issue کردم اما هیچ جوابی دریافت نکردم.

**Comment by sky93** [comment]
<div dir=rtl>
تپ‌سل برنامه‌نویس فلاتر ندارن. اون sdk که گذاشتن با متدچنل هست و توی نسخه release کلا کار نمی‌کنه. اگه با فلاتر کد می‌زنین بیخیال تپسل بشین.
</div>

**Comment by tavasolireza** [comment]
.منم همین مشکل رو داشتم و فقط با پاک‌کردن خطهای مربوط بهش توی پروگارد تونستم حلش کنم

**Comment by sky93** [comment]
<div dir="rtl">
منم با پاک‌کردن تپسل و استفاده از admob مشکلم کاملا برطرف شد.
</div>

**Comment by behrooz-fard** [comment]
سلام
شما می‌توانید از پلاگین فلاتر تپسل پلاس که مستندات آن در [این لینک](https://docs.tapsell.ir/plus-sdk/flutter/main/) قرار گرفته است استفاده نمایید.
همچنین اگر مشکلی روی آن داشتید در [ریپازیتوری](https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin) مربوط به خودش ایشو تعریف کنید.
