### ISSUE TITLE
Fatal Exception: java.lang.SecurityException getImeiForSlot: The user 10211 does not meet the requirements to access device identifiers. ir.tapsell.sdk.dataProvider.d.a

### ISSUE THREAD

**Issue by amirghm** [tapsellorg/TapsellPlusSDK-AndroidSample#16]
Hi, We have some issues with this error on some android 10 phones.
it seems you cannot get IMEI‌ information starting the android 10 version.

This error happened on `Galaxy A7 2018 Android 10`
We used `tapsell-plus 1.0.12` version
please fix this issue.

**Comment by Deepakkast** [comment]
Fatal Exception: java.lang.SecurityException
getSerial: The user 10397 does not meet the requirements to access device identifiers.
com.yandex.metrica.impl.ob.lt.a



in Android 10

**Comment by Deepakkast** [comment]
After upgrade target sdk 28 to 29

**Comment by behrooz-fard** [comment]
Hi dear Javad,
Sorry for the delay in response. We solved this bug in our last version. Please check our [document](https://docs.tapsell.ir/plus-sdk/android/main/).

**Comment by NOTiFYcouk** [comment]
@behrooz-fard Do you have your response in English? TIA.
