### ISSUE TITLE
راهی برای هولدر کردن تبلیغات

### ISSUE THREAD

**Issue by farzadnone** [tapsellorg/TapsellPlusSDK-AndroidSample#17]
سلام. چطوری میتونم یکبار که تبلیغات بنری یا محلی را دریافت کردم نگهش دارم. من تعداد زیادی فرگمنت دارم که خیلی هاشون ممکنه سریع باز و بسته بشن که اصلا فرصتی برای ارسال درخواست و فرصت نمایش آن نباشه.  میخام وقتی یه بنر دریافت کردم نگهش دارم در یک کلاس سینگلتون، تا هروقت که فرگمنت ها باز میشوند سریعا . نمایشش دهم. بدون نیاز به درخواست های بی جهت و الکی.
این هولدر را برای ادموب براحتی میشه نوشت. ولی اس دی کی تپسل متغییری را در دسترس نذاشته که بتوان ذخیرش کرد. تمام مراحل درخواست و نمایش تبلیغ در اس دی کی شما بصورت اینترفیس کالبک هستش و متغییری برای توسعه دهنده پاس نمیده. ارسال درخواست های بی فایده بدرد نمیخوره . بخصوص در مورد ادموب که تاثیر بدی روی محسابات و الگوریتم های ادموب داره. لطفا راهنمایی کنید.

```
AdHolder adHolder = TapsellPlus.createAdHolder(
		getActivity(),
		adsContainer,
		R.layout.tapsell_native_layout_small
);

// for native
TapsellPlus.requestNativeBanner(getActivity(), AdsHelper.TAPSELL_AD_UNIT_ID, new AdRequestCallback() {
	@Override
	public void response() {
		TapsellPlus.showAd(getActivity(), adHolder, AdsHelper.TAPSELL_AD_UNIT_ID);
	}

	@Override
	public void error(String message) {
	
		// for banner
		TapsellPlus.showBannerAd(
				getActivity(),
				adsContainer,
				AdsHelper.TAPSELL_AD_UNIT_ID,
				TapsellPlusBannerType.BANNER_320x50,
				new AdRequestCallback() {
					@Override
					public void response() {
					}

					@Override
					public void error(String message) {
					}
				});
	}

});
```

هیچ متغییری در دسترس نیست جهت نگه داری

**Comment by farzadnone** [comment]
کسی پاسخگو نیست؟

**Comment by behrooz-fard** [comment]
سلام فرزاد جان. بابت تاخیر در پاسخگویی صمیمانه عذرخواهی می‌کنم.
با استفاده از نسخه‌ی جدید [تپسل پلاس](https://docs.tapsell.ir/plus-sdk/android/main/) می‌توانید هر جا که خواستید درخواست تبلیغ را بدهید و صرفا ریسپانس آی‌دی تبلیغ را ذخیره کنید تا در فرگمنت دلخواهتان با استفاده از آن ریسپانس آی‌دی تبلیغ را نمایش دهید.

**Comment by farzadnone** [comment]
> 
> 
> سلام فرزاد جان. بابت تاخیر در پاسخگویی صمیمانه عذرخواهی می‌کنم.
> با استفاده از نسخه‌ی جدید [تپسل پلاس](https://docs.tapsell.ir/plus-sdk/android/main/) می‌توانید هر جا که خواستید درخواست تبلیغ را بدهید و صرفا ریسپانس آی‌دی تبلیغ را ذخیره کنید تا در فرگمنت دلخواهتان با استفاده از آن ریسپانس آی‌دی تبلیغ را نمایش دهید.

اگر ریسپانس آی دی را ذخیره کنم  این ضمانت وجود داره رسپانس ای دی رو بدم نمایش داده بشه؟ با فرض اینکه که دیستروید نکنم؟

**Comment by behrooz-fard** [comment]
تا زمانی که اپ بسته نشده باشد و تبلیغ را مصرف نکرده باشید بله می‌توانید از ریسپانس آی‌دی برای نمایش تبلیغ استفاده نمایید.
