### ISSUE TITLE
تغییر زبان (local)

### ISSUE THREAD

**Issue by mohamad62** [tapsellorg/TapsellPlusSDK-AndroidSample#2]
من وقتی از تپسل پلاس استفاده میکنم، زبان برنامه به زبان پیشفرض گوشی تغییر پیدا میکنه، زبان برنامه فارسیه، ولی زبان گوشی انگلیسی، وقتی کلاس تپسل پلاس فراخوانی میشه زبان برنامه هم انگلیسی میشه

**Comment by behdad222** [comment]
سلام
این مورد به تپسل ربط نداره
خود اندروید همیشه سعی میکنه به زبان دیفالت برگرده
و شما باید همیشه سعی کنید جلوش رو بگیرید
