### ISSUE TITLE
https://dl.bintray.com -> Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by mhkarami** [tapsellorg/TapsellPlusSDK-AndroidSample#22]
Could not GET 'https://dl.bintray.com/tapsellorg/maven/ir/tapsell/plus/tapsell-plus-sdk-android/1.2.3-rc4/tapsell-plus-sdk-android-1.2.3-rc4.pom'. Received status code 403 from server: Forbidden

bintray does not service any more. you should create jfrog account
امکان استفاده از بینتری دیگر وجود ندارد و کتابخانه تپسل به پروژه اضافه نمیشود .آدرس کتابخانه با جیفراگ باید جایگزین شود

**Comment by behrooz-fard** [comment]
سلام دوست عزیز
سمپل و مستندات به‌روز شده و می‌توانید استفاده کنید.
https://docs.tapsell.ir/plus-sdk/android/main/#v126---20210504
