### ISSUE TITLE
Unresolved reference: Gson

### ISSUE THREAD

**Issue by mhkarami** [tapsellorg/TapsellPlusSDK-AndroidSample#23]
بعد از اضافه کردن کتابخانه ورژن 1.2.6 ایمپورت های انجام شده با کتابخانه جیسون توسط اندروید استودیو شناسایی نمیشوند 

```
dependencies {
      ....

    implementation 'ir.tapsell.plus:tapsell-plus-sdk-android:1.2.6'

    //for adMob
    implementation 'com.google.android.gms:play-services-ads:19.6.0'

    implementation ("com.google.android.gms:play-services-base:17.5.0"){
        exclude group: 'com.android.support'
    }
    implementation ("com.google.android.gms:play-services-ads-identifier:17.0.0"){
        exclude group: 'com.android.support'
    }

    //retrofit
    def retrofit_version = "2.9.0"
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
//اضافه کردن کتابخانه جیسون هم تاثیری نداشت
//implementation 'com.google.code.gson:gson:2.8.6'
}
```

رفرنس های زیر با خطا مواجه میشوند : 
```
import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName
import  com.google.gson.Gson
import com.google.gson.GsonBuilder
و دیگر ایپورت ها با پیشوند 
`com.google.gson`
```

راهکارهای زیر را هم تست کرده ام:
- clean project
- invalidate catch and restart
- delete .idea and .build folder -> restart android studio
- restart PC
- delete libraries from dependencies -> invalidate catch and restart -> add libraries to dependencies 
- update Gradle
- add `implementation 'com.google.code.gson:gson:2.8.6'`
-  exclude group: `com.google.gson` from Tapsell library: `implementation 'ir.tapsell.plus:tapsell-plus-sdk-android:1.2.6'`
- change `allprojects { repositories { ` order
- create new android project and add the libraries
- ...

**Comment by behrooz-fard** [comment]
آیا روی همین پروژه هم امتحان کردید؟
لطفا از برنچ مستر پروژه را بگیرید و کتابخانه‌ای را که می‌خواهید اضافه نمایید.
ما تست کردیم و مشکلی از این جهت وجود نداشت.

**Comment by mhkarami** [comment]
این مراحل را انجام دادم :
برنچ مستر را دانلود کردم و اکسترکت کردم
تمامی پروژه های باز در اندروید استدیو رابستم
برنچ مستر را با اندروید استدیو باز کردم و ابزار رفع تحریم را روشن کردم تا پروژه کامل سینک شود
کتابخانه رتروفیت را به پروژه اضافه کردم و پروژه را سینک کردم
کلاسی ساختم که از جیسون استفاده کند 
نتیجه : جیسون و تمامی زیر کلاس های
 `com.google.gson`
 توسط اندروید استدیو شناسایی نشدند(عکس 1)

![pic1](https://user-images.githubusercontent.com/50570349/117537826-ab9f9c80-b018-11eb-9a71-0e164afb6e77.jpg)

سپس کتابخانه تپسل را حذف کردم و تمامی ارور های ایجاد شده در برنامه به واسطه حذف کتابخانه تپسل را برطرف کردم و سینک کردم
 ارور تمامی ایمپورت ها ی جیسون برطرف شدند(عکس2)

![pic2](https://user-images.githubusercontent.com/50570349/117537877-e43f7600-b018-11eb-8a62-e93a8f983f8b.jpg)

**Comment by behrooz-fard** [comment]
سلام
لطفا با نسخه‌ی جدید ۲.۱.۰ هم امتحان کنید که این مشکل وجود دارد؟

**Comment by mhkarami** [comment]
سمپل پروژکت جدید رو دانلود کردم و تمامی مراحل قبل رو طی کردم ولی بازم ارور دارد

![p1](https://user-images.githubusercontent.com/50570349/117770957-d5400a00-b24a-11eb-888d-0e77fd70e0f6.jpg)

**Comment by behrooz-fard** [comment]
سلام
دو کتابخانه‌ای که قصد استفاده دارید، به وسیله‌ی تپسل به پروژه‌تان اضافه می‌شود.
لطفا از گریدل خود حذفشان کنید و سپس به استفاده از آن‌ها در کد خودتان بپردازید.
https://repo1.maven.org/maven2/ir/tapsell/sdk/tapsell-sdk-android/4.7.0/tapsell-sdk-android-4.7.0.pom

**Comment by mhkarami** [comment]
سپاس راهنمایی خوبی بود. جیسون را از کتابخانه تپسل حذف کردم و مشکل برطرف شد
```
    implementation('ir.tapsell.plus:tapsell-plus-sdk-android:2.1.0')
            {
                exclude group: 'com.google.code.gson'
            }
```
