### ISSUE TITLE
چرا کسی پاسخگو نیست؟ - خیلی ها هستن که میتونند کمک کنند ولی انگار از سمت تپسل کسی نیست!!

### ISSUE THREAD

**Issue by hpn33** [tapsellorg/TapsellPlusSDK-AndroidSample#25]
با سلام
چرا پاسخگوییتون اینقدر ضعیفه
من یه مشکل با فلاتر دارم
یک نفر اون مشکلو حل کرده و پل ریکست داده ولی هیچ کس نبوده تا درخواستشونو بررسی کنه

بحث معلومه
هر روز تغییراتی در پلتفرم ها ایجاد میشه واگر با این تغییرات هماهنگ نشیدم شاید یه خروجی ساده هم نتونیم بگیریم
لطفا بخش برنامه نویسی را فعالتر کنید

**Comment by behrooz-fard** [comment]
سلام دوست عزیز
پول ریکوئستی که می‌فرمایید کجاست؟
نسخه‌ی جدید فلاتر تپسل پلاس هم اخیرا منتشر شده است و ممنون می‌شوم اگر موردی در آن خصوص هست روی ریپازیتوری مربوط به خودش اعلام کنید.

**Comment by hpn33** [comment]
سلام
مثل اینکه الان وضع بهتر شده یکی دو ماه پیش که به نظر میرسید خبری نیست

به زمان پاسخ ها نگاه کنید
https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/issues
برای همین امروزه

در مورد پول ریکوئست اشتباه از من بود

ممنون از پاسخگوییتون
@behrooz-fard

**Comment by behrooz-fard** [comment]
ما تمام تلاشمون را خواهیم کرد تا فرایند پشتیبانی فنی را بهبود دهیم. ممنون از شما بابت گزارش‌تون.
@hpn33
