### ISSUE TITLE
Tapsell Plus is not Initialized!

### ISSUE THREAD

**Issue by farzadnone** [tapsellorg/TapsellPlusSDK-AndroidSample#27]
بنده اینیشیالایز کردم. اینیشیالایز فقط یکبار در اپ اجرا میشه. هرچقدراپ را باز میکنم دیگه اینیشیالایز اجرا نمیشه. مشکل چیست؟ حتی متد زیر هم کال نمیشه:
`TapsellPlusInitListener `

version: 'ir.tapsell.plus:tapsell-plus-sdk-android:2.1.2'
devices: all

**Comment by farzadnone** [comment]
اخرین نسخه شما یعنی 2.1.2 با

**Comment by farzadnone** [comment]
اخرین نسخه شما یعنی 2.1.2 با
`com.google.android.gms:play-services-ads:20.2.0`
سازگار نیست.
لطفا بروز تر باشید.

**Comment by behrooz-fard** [comment]
سلام دوست عزیز
نسخه‌های شبکه‌های تبلیغاتی سازگار با تپسل پلاس را در [این لینک](https://docs.tapsell.ir/plus-sdk/android/add-adnetworks/) می‌توانید مشاهده کنید.
طبیعتا نسبت به آپدیت به آخرین نسخه‌ی هر شبکه ممکن است کمی تاخیر داشته باشیم امّا حتما در هر نسخه از تپسل پلاس سعی می‌شود از جدیدترین نسخه‌های شبکه‌های تبلیغاتی استفاده گردد.

**Comment by behrooz-fard** [comment]
سلام دوست عزیز
نسخه‌های شبکه‌های تبلیغاتی سازگار با تپسل پلاس را در [این لینک](https://docs.tapsell.ir/plus-sdk/android/add-adnetworks/) می‌توانید مشاهده کنید.
طبیعتا نسبت به آپدیت به آخرین نسخه‌ی هر شبکه ممکن است کمی تاخیر داشته باشیم امّا حتما در هر نسخه از تپسل پلاس سعی می‌شود از جدیدترین نسخه‌های شبکه‌های تبلیغاتی استفاده گردد.
