### ISSUE TITLE
react-native module

### ISSUE THREAD

**Issue by Schabaani** [tapsellorg/TapsellPlusSDK-AndroidSample#3]
ماژول ری اکت نیتوش هم هست یا خودمون باید پیاده سازی کنیم؟

**Comment by behdad222** [comment]
سلام
فعلا آماده نشده

**Comment by behrooz-fard** [comment]
سلام دوست عزیز
می‌توانید از پلاگین ری‌اکت‌نیتیو تپسل پلاس که در [این لینک](https://docs.tapsell.ir/plus-sdk/reactnative/main/) مستندات آن قرار گرفته است استفاده نمایید.
@Schabaani
