### ISSUE TITLE
Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by rezaaaaaaaaaaa** [tapsellorg/TapsellPlusSDK-AndroidSample#30]
> Task :app:processDebugManifest FAILED
[ir.tapsell.sdk:tapsell-sdk-android:4.7.2] C:\Users\reza\.gradle\caches\transforms-2\files-2.1\0494ca1fb72e832df07dc01ac94098b4\jetified-tapsell-sdk-android-4.7.2\AndroidManifest.xml:24:9-55 Error:
	Missing 'package' key attribute on element package at [ir.tapsell.sdk:tapsell-sdk-android:4.7.2] AndroidManifest.xml:24:9-55
[ir.tapsell.sdk:tapsell-sdk-android:4.7.2] C:\Users\reza\.gradle\caches\transforms-2\files-2.1\0494ca1fb72e832df07dc01ac94098b4\jetified-tapsell-sdk-android-4.7.2\AndroidManifest.xml Error:
	Validation failed, exiting

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

این خطا برای چیست؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
مانیفست رو میگه که نقص داره. احتمالا بخاطر jetifier اینطوری شده.
این آدرس رو حذف کنید تا دوباره jetify انجام بشه:

</div>
<div dir='rtl'>

`C:\Users\reza.gradle\caches\transforms-2\files-2.1\0494ca1fb72e832df07dc01ac94098b4\jetified-tapsell-sdk-android-4.7.2\`

</div>

<div dir='rtl'>
برای اطمینان میتونید برید از توی کش گریدل tapsell رو پاک کنید تو کیسی که دانلودش از گریدل مشکل دار انجام شده باشه
</div>

**Comment by mahdi-malv** [comment]
@rezaaaaaaaaaaa مشکل حل شد؟

**Comment by rezaaaaaaaaaaa** [comment]
بله گریدل رو به اخرین ورژن اپدیت کردم درست شد

**Comment by appikoo** [comment]
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

منم دارم مشکلو

**Comment by mahdi-malv** [comment]
@appikoo 
بقیه‌ی ارور؟

**Comment by appikoo** [comment]
کلا همین ارور و میده
