### ISSUE TITLE
🐛  باگ: cert_verify_callback 

### ISSUE THREAD

**Issue by Mori-hub** [tapsellorg/TapsellPlusSDK-AndroidSample#35]
<div dir='rtl'>

**شرح باگ در پلاگین**:
سلام وقت بخیر ,
تنظیمات برای نسخه جدید انجام شده اما این خطا نمایش داده می شود
 implementation 'ir.tapsell.plus:tapsell-plus-sdk-android:2.1.3'

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
 ssl=0xae77ce40 cert_verify_callback x509_store_ctx=0x9f3c339c arg=0x0
ssl=0xae77ce40 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود
اول از همه ممنون بابت استفاده‌ی درست از Issue template

این خطا خیلی مبهمه و نمی‌تونم تشخیص بدم بخاطر چی میتونه اتفاق افتاده باشه

ممنون میشم `TapsellPlus.setDebugMode(Log.DEBUG);` رو امتحان کنید و لاگ کاملتری ارسال کنید

</div>

**Comment by mahdi-malv** [comment]
Closing. Feel free to re-open if the problem still exists.
