### ISSUE TITLE
تغییر مقداردهی اولیه از اکتویتی به کانتکست

### ISSUE THREAD

**Issue by farzadnone** [tapsellorg/TapsellPlusSDK-AndroidSample#4]
مقداردهی اولیه یا همان اینیشیلایز کردن با اکتویتی مشکلی که داره این است که ممکن است اصلا اکتویتی دیگری صدا زده بشه و اصلا  اکتویتی اصلی برنامه نیازی به بالا آمدن نباشه. مثلا اکتویتی نمایش نوتیفیکیشن و یا اکتویتی هایی که سینگل وورک باشن.
اگر اکتویتی را به کانتکست تبدیل کنید میتوان یکبار برای همه جا در کلاس اپلیکیشن مقداردهی اولیه بشه.
چون دسترسی به اکتویتی در کلاس اپلیکیشن وجود نداره.

در برنامه های پیچیده چنین مشلاتی بوحود میاد و اگر هواس برنامه نویس جمع نباشه دچار عدم نمایش تبلیغ میشه.

change: 
`TapsellPlus.initialize(activity, TAPSELL_KEY);`

to:
`TapsellPlus.initialize(context, TAPSELL_KEY);`

اگر نکته ای هست بفرمایید

**Comment by behdad222** [comment]
ما برای init کردن نیازی به اکتیویتی نداریم
اما برخی از ادنتورک‌های ثانویه نیاز دارند و این ایجاد مشکل میکنه
در هر صورت از چند نسخه قبل امکان init کردن با context رو فراهم کردیم و میتونید ازش استفاده کنید
و هر زمان که اکتیویتی رو ازتون گرفتیم ادنتورک‌هایی که به اکتیویتی نیاز دارند رو init میکنیم

**Comment by farzadnone** [comment]
بدلیل اینکه میخام از جدیدترین نسخه شما استفاده کنم مجبورم در چندین اکتیویتی مقداردهی اولیه انجام دهم. چندین بار اینیشیلایز کردن مشکلی که نداره؟

**Comment by behdad222** [comment]
گفتم از چند نسخه قبل امکان init کردن با context رو فراهم کردیم
میتونید از اون استفاده کنید
مشکلی هم پیش نمیاد

**Comment by farzadnone** [comment]
اوکی ممنون.
