### ISSUE TITLE
🐛  باگ: Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by MasterAlive** [tapsellorg/TapsellPlusSDK-AndroidSample#40]
<div dir='rtl'>

**شرح باگ در پلاگین**:
ارور گریدل برای خروجی گرفتن از برنامه.
حتی نمونه آماده ای که توی داکیومنتهای تپسل هست هم همین ارور رو میده.

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\2020.1.6f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\2020.1.6f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-5.6.4.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':launcher:debugRuntimeClasspath'.
   > Could not resolve ir.tapsell.plus:tapsell-plus-sdk-unity:1.0.12.
     Required by:
         project :launcher > project :unityLibrary
      > Could not resolve ir.tapsell.plus:tapsell-plus-sdk-unity:1.0.12.
         > Could not get resource 'https://jcenter.bintray.com/ir/tapsell/plus/tapsell-plus-sdk-unity/1.0.12/tapsell-plus-sdk-unity-1.0.12.pom'.
            > Could not GET 'https://jcenter.bintray.com/ir/tapsell/plus/tapsell-plus-sdk-unity/1.0.12/tapsell-plus-sdk-unity-1.0.12.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
]
stdout[
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <8c48e4bc2ff34638b69095cbb65e2e27>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``
com.Master.Alive.Zarb60

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by mahdi-malv** [comment]
از نسخه‌ی آخر پلاگین استفاده کنید. ۱.۰.۱۲ توی jcenter هست که دیگه آپدیت نمیگیره. ورژن‌های جدید توی mavenCentral آپلود میشه
https://docs.tapsell.ir/plus-sdk/unity/main/

**Comment by MasterAlive** [comment]
مشکل داخل انجین یونیتیه
