### ISSUE TITLE
[Unity] Failure in Unity

### ISSUE THREAD

**Issue by AhmadrezaHossini** [tapsellorg/TapsellPlusSDK-AndroidSample#43]
سلام و خسته نباشید خدمت تیم خوب تپسل من در زمان بیلد گرفتن اندروید وقتی پکیج تپسل وارد کردم به خطای graidle failed بر میخورم و نمیدونم باید چیکارش کنم ممنون میشم راهنماییم کنید

**Comment by MortezaNedaei** [comment]
با سلام. ممنون از گزارش خطا.

 این مشکل مرتبط با سمپل اندروید نیتیو هست یا سمپل یونیتی؟
درصورتیکه مرتبط با یونیتی هست، میتوانید این مشکل را در ریپازیتوری های مرتبط با یونیتی به یکی آدرس های زیر اضافه کنید.

* [پروژه‌ی نمونه مناسب برای Unity 2020.3.9f1 LTS](https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2020)

* [پروژه‌ی نمونه مناسب برای Unity 2019.4.11f1 LTS](https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2019)

* [پروژه‌ی نمونه مناسب برای Unity 2018.4.26f1 LTS](https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2018)

اما در صورتیکه مشکل مرتبط با سمپل اندروید هست، لطفا متن کامل خطا یا لاگ مرتبط یا هر گونه اطلاعات اضافی را به طور کامل ارسال کنید تا امکان بررسی بهتر وجود داشته باشد.

با تشکر.

**Comment by AhmadrezaHossini** [comment]
راستش این ارورهارو بهم میده و فکر میکنم سمت یونیتی هستش (عکسش براتون میفرستم)
![Screenshot (299)](https://user-images.githubusercontent.com/63165112/161046265-0dd12b3e-f0fb-434c-abfb-0f94a39b3c64.png)

**Comment by AhmadrezaHossini** [comment]
![Uploading Screenshot (298).png…]()

**Comment by AhmadrezaHossini** [comment]
![Screenshot (298)](https://user-images.githubusercontent.com/63165112/161048341-7c18d96f-d3e7-490b-9d25-64e6db02a6b4.png)

**Comment by AhmadrezaHossini** [comment]
کسی از دوستان تپسل نیست این موضوع جواب بده من انتشار بازیم همین جور داره میوفته عقب بخاطر همین تبلیغ تپسل

**Comment by mahdi-malv** [comment]
سلام
لطفا خطا رو واضح بفرستید
روی آیتم دومی که در مورد گریدل هست کلیک کنید و دیتای stderr[] رو ارسال کنید

**Comment by AhmadrezaHossini** [comment]
ببخشید متوجه نمیشم میشه تماس تصویری برقرار کنیم و خطارو  دقیق بررسی کنیم؟

**Comment by AhmadrezaHossini** [comment]
> سلام لطفا خطا رو واضح بفرستید روی آیتم دومی که در مورد گریدل هست کلیک کنید و دیتای stderr[] رو ارسال کنید

..

**Comment by MortezaNedaei** [comment]
با سلام.
برای اینکه بدونیم چه مشکلی وجود داره، لازم هست متن دقیق خطا را ارسال کنید.
در عکسی که فرستادین، خطا کامل مشخص نیست.
در عکس اول، روی خطای دوم( که در زیر عکس مشخصه،) کلیک کنید، میتونید جزئیات بهتری از خطا رو ببینید.
لطفا متن کامل این جزئیات رو ارسال کنین.
@AhmadrezaHossini

**Comment by mahdi-malv** [comment]
Closing. Feel free to re-open if the problem still exists.
