### ISSUE TITLE
🐛  باگ: Error inflating class com.google.android.gms.ads.nativead.NativeAdView

### ISSUE THREAD

**Issue by HadiDortaj** [tapsellorg/TapsellPlusSDK-AndroidSample#44]
<div dir='rtl'>
متاسفانه داکیومنتتون خیلی ضعیفه. من تو داکیومنت ها قسمتی برا اضافه کردن play-services-ads به پروژه ندیدم. نیازی هم بهش نداشتم چون فعلا پروژه تو گوگل پلی نیست. ولی موقع نشون دادن بنر همسان این خطای پایین اتفاق می افتاد.
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.google.android.gms.ads.nativead.NativeAdView
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.google.android.gms.ads.nativead.NativeAdView
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.nativead.NativeAdView"

 قسمت بد اش هم اینه که به هیچ عنوان لاگ این خطا چاپ نمیشه و من توسط crash reporter این خطا رو دیدم. این خطا با اضافه کردن play-services-ads به پروژه درست شد ولی بهتره هم این خطا رو بهبود بدین هم داکیومنت ها رو بهتر کنید.
</div>

**Comment by mahdi-malv** [comment]
سلام
ممنون از اینکه اطلاع دادید این مورد رو
بله این نقص توی مستندات هست. حتما مشکل رو مرتفع خواهیم کرد.

با تشکر

**Comment by mahdi-malv** [comment]
Issue's been fixed in docs. Closing
