### ISSUE TITLE
[Unity] Gradle build failed , see the console for details

### ISSUE THREAD

**Issue by Nafiseh216** [tapsellorg/TapsellPlusSDK-AndroidSample#45]
بعد از اضافه کردن بکیج تپسل پلاس در یونیتی هنگام Build  کردن خطای Gradle build failed , see the console for details نمایش داده می شود .
در صورتی که بدون استفاده از پکیج پروژه بدون هیچ خطایی Build  می شود. 
نسخه یونیتی مورد استفاده 2020.2.7f1 می باشد.
لطفاً راهنمایی کنید.

**Comment by mahdi-malv** [comment]
سلام
محتوای `stderr[]` رو که مربوط به خطای گریدل هست رو ارسال کنید که بدونیم خطا چی هست و چرا build به مشکل خورده
با تشکر

**Comment by Nafiseh216** [comment]
سپاسگزارم
![gradle1](https://user-images.githubusercontent.com/96763796/163798383-eee0ad89-ce90-4f7a-ab04-360f5fc8957e.png)

![gradle2](https://user-images.githubusercontent.com/96763796/163798470-12887740-6777-40c8-9125-39565e104580.png)
![gradle3](https://user-images.githubusercontent.com/96763796/163798476-5b8662dc-9b85-4b96-826f-bbe9c420d6dc.png)
![gradle4](https://user-images.githubusercontent.com/96763796/163798479-fa0bb44a-8a39-4983-b4ae-fb16a3ca3046.png)

**Comment by mahdi-malv** [comment]
![image](https://user-images.githubusercontent.com/21319971/163799901-8b5f9ad2-dc27-410e-b673-901727e62e23.png)
مطابق این خطها دلیل بروز خطا ارور سینتکسی توی gradle نهایی هست
لطفا بررسی کنید که چه خطی مشکل داره. خط داره میگه ... توی فایل هست که نباید باشه

**Comment by Nafiseh216** [comment]
سلام روزتون بخیر

ممنون از راهنماییتون

**Comment by Nafiseh216** [comment]
عذر میخواهم مجدد مزاحمتون شدم
خطای قبلی برطرف شد ولی متاسفانه خطاهای زیر نمایش داده میشود.


![error1](https://user-images.githubusercontent.com/96763796/163938455-fbe3b675-11f4-4f53-9e89-ebb7ed1e93ac.png)
![error2-1](https://user-images.githubusercontent.com/96763796/163938466-274d3125-40e9-49ad-9e61-36aa94a7a286.png)
![error2-2](https://user-images.githubusercontent.com/96763796/163938471-03cb552e-e31a-4acb-8037-5a7dfb338f27.png)
![error3-1](https://user-images.githubusercontent.com/96763796/163938479-1c3ddf14-95d8-436b-ac58-15eaf21cd469.png)
![error3-2](https://user-images.githubusercontent.com/96763796/163938486-8ce362da-1374-4e96-9a2b-624302b8df92.png)
![error3-3](https://user-images.githubusercontent.com/96763796/163938496-f01efc8e-75b5-48be-ba1c-57e7c6d55876.png)

**Comment by Nafiseh216** [comment]
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_77\bin\java.exe -classpath "C:\gradle\gradle-6.9\lib\gradle-launcher-6.9.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':launcher:debugRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-appset:16.0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-appset/16.0.2/play-services-appset-16.0.2.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-appset/16.0.2/play-services-appset-16.0.2.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-appset-16.0.2.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-appset.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7
   > Could not find com.google.android.gms:play-services-auth:16.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-auth/16.0.1/play-services-auth-16.0.1.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-auth/16.0.1/play-services-auth-16.0.1.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-auth-16.0.1.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-auth.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7
   > Could not find com.google.android.gms:play-services-ads-identifier:17.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-ads-identifier-17.0.0.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-ads-identifier.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7 > ir.tapsell.sdk:tapsell-sdk-android:4.7.4
   > Could not find com.google.android.gms:play-services-appset:16.0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-appset/16.0.2/play-services-appset-16.0.2.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-appset/16.0.2/play-services-appset-16.0.2.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-appset-16.0.2.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/play-services-appset.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7 > ir.tapsell.sdk:tapsell-sdk-android:4.7.4
   > Could not find androidx.fragment:fragment:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.0.0/fragment-1.0.0.pom
       - https://jcenter.bintray.com/androidx/fragment/fragment/1.0.0/fragment-1.0.0.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/fragment-1.0.0.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/fragment.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7 > com.github.bumptech.glide:glide:4.12.0
   > Could not find androidx.vectordrawable:vectordrawable-animated:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable-animated/1.0.0/vectordrawable-animated-1.0.0.pom
       - https://jcenter.bintray.com/androidx/vectordrawable/vectordrawable-animated/1.0.0/vectordrawable-animated-1.0.0.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/vectordrawable-animated-1.0.0.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/vectordrawable-animated.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7 > com.github.bumptech.glide:glide:4.12.0
   > Could not find androidx.exifinterface:exifinterface:1.2.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/exifinterface/exifinterface/1.2.0/exifinterface-1.2.0.pom
       - https://jcenter.bintray.com/androidx/exifinterface/exifinterface/1.2.0/exifinterface-1.2.0.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/exifinterface-1.2.0.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/exifinterface.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7 > com.github.bumptech.glide:glide:4.12.0
   > Could not find androidx.annotation:annotation:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/annotation/annotation/1.0.0/annotation-1.0.0.pom
       - https://jcenter.bintray.com/androidx/annotation/annotation/1.0.0/annotation-1.0.0.pom
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/annotation-1.0.0.jar
       - file:/D:/unity Project/Tapsell/Temp/gradleOut/unityLibrary/libs/annotation.jar
     Required by:
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7 > com.github.bumptech.glide:okhttp3-integration:4.11.0
         project :launcher > project :unityLibrary > ir.tapsell.plus:tapsell-plus-sdk-unity:2.1.7 > com.github.bumptech.glide:glide:4.12.0 > com.github.bumptech.glide:gifdecoder:4.12.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[

> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <53eba1e5422a4c52b9cf57c0e90cf697>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <b76552deb4624e46abeeb45b48b7f62d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by mahdi-malv** [comment]
سلام مجدد
به نظر میرسه ۴۰۳ میخوره که پکیج‌ها دانلود نمیشن
از [شکن ](https://shecan.ir/)یا FOD ([گیتهاب](https://github.com/freedomofdevelopers/fod)) یا یه وی‌پی‌ان که بتونه پکیج‌ها رو دانلود کنه استفاده کنید. سرورهای دانلود پکیج‌ها تحریم هستن

پ.ن: لطفا تا مشکلتون حل نشده ایشو رو تو وضعیت Open نگه دارید تا مطمئن شیم که مشکل حل و فصل شده. با تشکر

**Comment by Nafiseh216** [comment]
با استفاده از شکن مجدد خطاهای زیر نمایش داده شد
![error1](https://user-images.githubusercontent.com/96763796/163969756-8bc11bc6-9427-427b-9e0c-7c8de4e3def8.png)
![error2](https://user-images.githubusercontent.com/96763796/163969764-d1b23e9c-03c0-4bf4-bc65-84b396b3dcce.png)
![error3-1](https://user-images.githubusercontent.com/96763796/163969766-bb543e10-fafa-48c5-95d9-c5ab32d0a238.png)
![error3-2](https://user-images.githubusercontent.com/96763796/163969769-1d490177-2633-431f-a758-4406d44f1e4d.png)

**Comment by mahdi-malv** [comment]
AndroidX: https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2020/issues/7

**Comment by Nafiseh216** [comment]
سلام مجدد
ممنون از راهنماییتون

خطای قبلی برطرف شد ولی متاسفانه خطای زیر نمایش داده می شود .

از آخرین نسخه تپسل پلاس استفاده کردم.

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_77\bin\java.exe -classpath "C:\gradle\gradle-6.9\lib\gradle-launcher-6.9.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':launcher:debugRuntimeClasspath'.
   > Failed to transform play-services-ads-identifier-17.0.0.aar (com.google.android.gms:play-services-ads-identifier:17.0.0) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find play-services-ads-identifier-17.0.0.aar (com.google.android.gms:play-services-ads-identifier:17.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.aar
   > Failed to transform play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/18.0.0/play-services-basement-18.0.0.aar
   > Failed to transform play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/18.0.0/play-services-basement-18.0.0.aar
   > Failed to transform play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/18.0.0/play-services-basement-18.0.0.aar
   > Failed to transform play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/18.0.0/play-services-basement-18.0.0.aar
   > Failed to transform play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/18.0.0/play-services-basement-18.0.0.aar
   > Failed to transform play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/18.0.0/play-services-basement-18.0.0.aar
   > Failed to transform play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find play-services-basement-18.0.0.aar (com.google.android.gms:play-services-basement:18.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/18.0.0/play-services-basement-18.0.0.aar
   > Failed to transform fragment-1.0.0.aar (androidx.fragment:fragment:1.0.0) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find fragment-1.0.0.aar (androidx.fragment:fragment:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.0.0/fragment-1.0.0.aar
   > Failed to transform fragment-1.0.0.aar (androidx.fragment:fragment:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find fragment-1.0.0.aar (androidx.fragment:fragment:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.0.0/fragment-1.0.0.aar
   > Failed to transform fragment-1.0.0.aar (androidx.fragment:fragment:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find fragment-1.0.0.aar (androidx.fragment:fragment:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.0.0/fragment-1.0.0.aar
   > Failed to transform vectordrawable-animated-1.0.0.aar (androidx.vectordrawable:vectordrawable-animated:1.0.0) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find vectordrawable-animated-1.0.0.aar (androidx.vectordrawable:vectordrawable-animated:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable-animated/1.0.0/vectordrawable-animated-1.0.0.aar
   > Failed to transform exifinterface-1.2.0.aar (androidx.exifinterface:exifinterface:1.2.0) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find exifinterface-1.2.0.aar (androidx.exifinterface:exifinterface:1.2.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/exifinterface/exifinterface/1.2.0/exifinterface-1.2.0.aar
   > Failed to transform legacy-support-core-ui-1.0.0.aar (androidx.legacy:legacy-support-core-ui:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find legacy-support-core-ui-1.0.0.aar (androidx.legacy:legacy-support-core-ui:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-ui/1.0.0/legacy-support-core-ui-1.0.0.aar
   > Failed to transform legacy-support-core-ui-1.0.0.aar (androidx.legacy:legacy-support-core-ui:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find legacy-support-core-ui-1.0.0.aar (androidx.legacy:legacy-support-core-ui:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-ui/1.0.0/legacy-support-core-ui-1.0.0.aar
   > Failed to transform legacy-support-core-utils-1.0.0.aar (androidx.legacy:legacy-support-core-utils:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find legacy-support-core-utils-1.0.0.aar (androidx.legacy:legacy-support-core-utils:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-utils/1.0.0/legacy-support-core-utils-1.0.0.aar
   > Failed to transform legacy-support-core-utils-1.0.0.aar (androidx.legacy:legacy-support-core-utils:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find legacy-support-core-utils-1.0.0.aar (androidx.legacy:legacy-support-core-utils:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-utils/1.0.0/legacy-support-core-utils-1.0.0.aar
   > Failed to transform loader-1.0.0.aar (androidx.loader:loader:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find loader-1.0.0.aar (androidx.loader:loader:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/loader/loader/1.0.0/loader-1.0.0.aar
   > Failed to transform loader-1.0.0.aar (androidx.loader:loader:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find loader-1.0.0.aar (androidx.loader:loader:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/loader/loader/1.0.0/loader-1.0.0.aar
   > Failed to transform lifecycle-viewmodel-2.0.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find lifecycle-viewmodel-2.0.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.0.0/lifecycle-viewmodel-2.0.0.aar
   > Failed to transform lifecycle-viewmodel-2.0.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find lifecycle-viewmodel-2.0.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.0.0/lifecycle-viewmodel-2.0.0.aar
   > Failed to transform vectordrawable-1.0.0.aar (androidx.vectordrawable:vectordrawable:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find vectordrawable-1.0.0.aar (androidx.vectordrawable:vectordrawable:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable/1.0.0/vectordrawable-1.0.0.aar
   > Failed to transform viewpager-1.0.0.aar (androidx.viewpager:viewpager:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find viewpager-1.0.0.aar (androidx.viewpager:viewpager:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.aar
   > Failed to transform coordinatorlayout-1.0.0.aar (androidx.coordinatorlayout:coordinatorlayout:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find coordinatorlayout-1.0.0.aar (androidx.coordinatorlayout:coordinatorlayout:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/coordinatorlayout/coordinatorlayout/1.0.0/coordinatorlayout-1.0.0.aar
   > Failed to transform drawerlayout-1.0.0.aar (androidx.drawerlayout:drawerlayout:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find drawerlayout-1.0.0.aar (androidx.drawerlayout:drawerlayout:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/drawerlayout/drawerlayout/1.0.0/drawerlayout-1.0.0.aar
   > Failed to transform slidingpanelayout-1.0.0.aar (androidx.slidingpanelayout:slidingpanelayout:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find slidingpanelayout-1.0.0.aar (androidx.slidingpanelayout:slidingpanelayout:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/slidingpanelayout/slidingpanelayout/1.0.0/slidingpanelayout-1.0.0.aar
   > Failed to transform customview-1.0.0.aar (androidx.customview:customview:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find customview-1.0.0.aar (androidx.customview:customview:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/customview/customview/1.0.0/customview-1.0.0.aar
   > Failed to transform customview-1.0.0.aar (androidx.customview:customview:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find customview-1.0.0.aar (androidx.customview:customview:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/customview/customview/1.0.0/customview-1.0.0.aar
   > Failed to transform customview-1.0.0.aar (androidx.customview:customview:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find customview-1.0.0.aar (androidx.customview:customview:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/customview/customview/1.0.0/customview-1.0.0.aar
   > Failed to transform customview-1.0.0.aar (androidx.customview:customview:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find customview-1.0.0.aar (androidx.customview:customview:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/customview/customview/1.0.0/customview-1.0.0.aar
   > Failed to transform customview-1.0.0.aar (androidx.customview:customview:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find customview-1.0.0.aar (androidx.customview:customview:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/customview/customview/1.0.0/customview-1.0.0.aar
   > Failed to transform swiperefreshlayout-1.0.0.aar (androidx.swiperefreshlayout:swiperefreshlayout:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find swiperefreshlayout-1.0.0.aar (androidx.swiperefreshlayout:swiperefreshlayout:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/swiperefreshlayout/swiperefreshlayout/1.0.0/swiperefreshlayout-1.0.0.aar
   > Failed to transform asynclayoutinflater-1.0.0.aar (androidx.asynclayoutinflater:asynclayoutinflater:1.0.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find asynclayoutinflater-1.0.0.aar (androidx.asynclayoutinflater:asynclayoutinflater:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/asynclayoutinflater/asynclayoutinflater/1.0.0/asynclayoutinflater-1.0.0.aar
   > Failed to transform core-1.2.0.aar (androidx.core:core:1.2.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find core-1.2.0.aar (androidx.core:core:1.2.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/core/core/1.2.0/core-1.2.0.aar
   > Failed to transform core-1.2.0.aar (androidx.core:core:1.2.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find core-1.2.0.aar (androidx.core:core:1.2.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/core/core/1.2.0/core-1.2.0.aar
   > Failed to transform core-1.2.0.aar (androidx.core:core:1.2.0) to match attributes {artifactType=jar, org.gradle.status=release}.
      > Could not find core-1.2.0.aar (androidx.core:core:1.2.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/core/core/1.2.0/core-1.2.0.aar
   > Failed to transform core-1.2.0.aar (androidx.core:core:1.2.0) to match attributes {artifactType=jar, org.gradle.stat<message truncated>

**Comment by MortezaNedaei** [comment]
سلام.
گریدل نتونسته فایل های مربوطه رو از این لینک ها دانلود کنه و به نظر میرسه که مشکل نتورک یا پراکسی داشته باشید.
با وی پی ان مجدد بررسی کنید.

**Comment by mahdi-malv** [comment]
Closing. Please re-open if the issue still exists.
