### ISSUE TITLE
[Unity] crash app while showing rewarded video

### ISSUE THREAD

**Issue by mkfcga** [tapsellorg/TapsellPlusSDK-AndroidSample#46]
**logcat error:**
2022-04-19 13:51:00.206 21444-23504/? E/TAP_SDK_TapsellImp: tapsell imp error
2022-04-19 13:51:00.224 21444-21444/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.**.**, PID: 21444
    java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
        at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:53)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

تپسل پلاس بدون مشکل اینیشیال میشه اما موقع نمایش اپ کرش میکنه.
unity 2020.3

**Comment by mahdi-malv** [comment]
سلام

اگر توی  زونتون admob فعال باشه باید ادنتورک ادموب هم اضافه کنید چون بهش وابسته ست
https://docs.tapsell.ir/plus-sdk/unity/add-adnetworks/

لطفا ادموب رو هم اضافه کنید و بعدش تست کنید ببینید آیا باز هم اوکی هست یا نه

**Comment by mkfcga** [comment]
سلام ایدی ادبوب رو بردم تو منیفست اصلی درست شد.سوییچ کردم رو پلاس چون تپسل رو اندروید 4.4 خطای اس اس ال داشت.اما همچنان این خطا وجود داره
04-19 17:30:24.605 7413-7520/? E/TAP_SDK_WaterfallManag: onWaterfallFailed: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x894a2dc0: Failure in SSL library, usually a protocol error    error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x73ebdce0:0x00000000)04-19 17:30:24.635 3228-4110/? E/EnterpriseContainerManager: ContainerPolicy Service is not yet ready!!!04-19 17:30:24.875 7413-7413/? E/AndroidRuntime: FATAL EXCEPTION: main    Process: **, PID: 7413    java.lang.Error: FATAL EXCEPTION [main]    Unity version     : 2020.3.16f1    Device model      : samsung GT-I9500    Device fingerprint: samsung/ja3gub/ja3g:4.4.2/KOT49H/I9500UBUFNB3:user/release-keys    Build Type        : Release    Scripting Backend : IL2CPP    ABI               : armeabi-v7a    Strip Engine Code : true        Caused by: java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd        at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:53)        at android.os.Handler.handleCallback(Handler.java:733)        at android.os.Handler.dispatchMessage(Handler.java:95)        at android.os.Looper.loop(Looper.java:157)        at android.app.ActivityThread.main(ActivityThread.java:5356)        at java.lang.reflect.Method.invokeNative(Native Method)        at java.lang.reflect.Method.invoke(Method.java:515)        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)        at dalvik.system.NativeStart.main(Native Method)

    On Tuesday, April 19, 2022, 03:42:03 PM GMT+4:30, Mahdi Malvandi ***@***.***> wrote:  
 
 


سلام

اگر توی زونتون admob فعال باشه باید ادنتورک ادموب هم اضافه کنید چون بهش وابسته ست
https://docs.tapsell.ir/plus-sdk/unity/add-adnetworks/

لطفا ادموب رو هم اضافه کنید و بعدش تست کنید ببینید آیا باز هم اوکی هست یا نه
