### ISSUE TITLE
🚀 [Feature/Enhancement]: jetpack compose

### ISSUE THREAD

**Issue by razaghimahdi** [tapsellorg/TapsellPlusSDK-AndroidSample#48]
does this version support jetpack compose? or maybe any new update?

**Comment by mahdi-malv** [comment]
Currently the only way is to load a native view into your composables (As an `AndroidView` composable)

Let's leave this alive and I'll put it in our backlog.

**Comment by razaghimahdi** [comment]
would u give me better example how to set that with with androidview? for example just a standard banner, tnx

**Comment by MortezaNedaei** [comment]
@razaghimahdi You can use [TapsellPlus Jetpack Compose Sample](https://github.com/tapsellorg/TapsellPlusSDK-Jetpack-Compose-Sample)

**Comment by razaghimahdi** [comment]
Not bad, still should have separate library for that, anyway, thanks for answering after 6 month I guess :))
