### ISSUE TITLE
نمایش بنر همسان در لیست

### ISSUE THREAD

**Issue by abdollahammail** [tapsellorg/TapsellPlusSDK-AndroidSample#5]
سلام
سمپل کدی برای نمایش بنر در لیست وجود داره به صورت لیزی لود هست و اگر بخواهیم در لیستی که تمام داده ها از همون اول لود میشن استفاده کنیم به مشکل برمیخوریم، به عنوان مثال اگر بخواهیم بین هر سه سطر یک بنر نمایش بدیم و 12 سطر هم داشته باشیم باید همزمان 4 ریکوئست برای تبلیغ بفرستیم که تنها ریکوئست اول درست عمل میکنه و 3 ریکوئست بعدی با "اد آیدی" نال برمیگردن، ممنون میشم راهنمایی بفرمایید.

**Comment by behdad222** [comment]
در حال حاضر امکان چیزی که میگید نیست

**Comment by farzadnone** [comment]
@abdollahammail 
اولا اینکه این معقولانه نیست که بین هر سطر تبلیغ لود کنید.
دوما شما وقتی آرایه لیستت آماده میشه بده به آداپترت تا لیست و لود کنه و بعدش داخل هولدر آداپترت باید درخواست تبلیغ بدی هروقت تبلیغ اماده نمایش شد در کالبک مربوطه باید لیستتو نوتیفای کنی تا همون ویوی یا سطرت رفرش بشه. کلا نمایش تبلیغات در لیست یه چندتا نکته و قلق داره که  با تجربه بدست میاد. موفق باشی

**Comment by behdad222** [comment]
@abdollahammail 
درخواست تبلیغ داخل هولدر روش مناسبی نیست

**Comment by farzadnone** [comment]
@behdad222 
Manzooram dar **onCreateViewHolder** dar **RecyclerView** hast ke monjar mishe agar view az scroll ham kharej beshe view destry nashe va baghi bemoone.. dar **onBind** nabayad bashe.

**Comment by behdad222** [comment]
@abdollahammail 
روش قشنگی نیست
من پیشنهاد نمیدم

حتی کارایی مورد نیاز رو هم نداره

**Comment by abdollahammail** [comment]
@farzadnone 
منظورم هر سطر نبود، هر ۴ سطر یک تبلیغ بود.
این روش فکر نکنم جواب بده. احتمالا مجبورم توی کل لیست فقط یک تبلیغ قرار بدم. البته امیدوارم در ورژن‌های آینده راهی برای حل این مشکل پیداکنن دوستان چون خیلی طبیعیه که توی یک لیست ۱۰۰ عضوی بخوایم مثلا ۱۰ تا تبلیغ نمایش بدیم.

**Comment by behdad222** [comment]
@abdollahammail
 میتونید هر بار که تبلیغ آماده شد تو لیست insert کنید
