### ISSUE TITLE
🐛  باگ:  NativeBannerActivity مشکل پیاده سازی

### ISSUE THREAD

**Issue by esirahimian** [tapsellorg/TapsellPlusSDK-AndroidSample#50]
سلام 
داخل اکتیویتی NativeBannerActivity 
خط 37
R.layout.native_banner
چه لایوتیه تو لایوت ها نیست من هر لایوتی هم بهش میدم adnative کار نمیکنه تو لاگ هم میزنه ad is opened
لطفا راهنمایی کنید

  private void init() {
        adContainer = findViewById(R.id.adContainer);

        adHolder = TapsellPlus.createAdHolder(
                this, adContainer, R.layout.native_banner);

        requestAd();
    }

**Comment by esirahimian** [comment]
پیداش کردم لایوت خود ناتیو ویو هست

**Comment by MortezaNedaei** [comment]
سلام.
 مشکل حل شد؟ تبلیغ نمایش داده میشه؟
