### ISSUE TITLE
🐛  Error: Tapsell: Ad UnAvailable 

### ISSUE THREAD

**Issue by esirahimian** [tapsellorg/TapsellPlusSDK-AndroidSample#52]
<div dir='rtl'>

**شرح باگ در پلاگین**:
سلام وقتتون بخیر  
از پریروز این پروژرو که ازش بیلد گرفتم دیگه کار نمیکنه تست هاش 
این هم کد ارور 
TAP_SDK_TapsellNative: onFailed Ad UnAvailable
Tapsel: banner error All Ad Networks Returned Error! - {"TAPSELL":"Ad UnAvailable"}
</div>

**Comment by mahdi-malv** [comment]
سلام
لطفا مجددا تست کنید
سمت سرور موردی بوده که باید حل شده باشه
