### ISSUE TITLE
سلام دکمه بک در تبلیغات ویدیویی تپسل پلاس رو چجوری غیر فعال کنم

### ISSUE THREAD

**Issue by mohsen212168100** [tapsellorg/TapsellPlusSDK-AndroidSample#55]
سلام دکمه بک در تبلیغات ویدیویی تپسل پلاس رو چجوری غیر فعال کنم؟

**Comment by MortezaNedaei** [comment]
سلام وقتتون بخیر
لطفا با آیدی زیر در تلگرام در ارتباط باشید:
@TapsellTechSupport
