### ISSUE TITLE
🐛  باگ: generated source file should not be edited

### ISSUE THREAD

**Issue by 75q399996666n** [tapsellorg/TapsellPlusSDK-AndroidSample#56]
<div dir='rtl'>

**شرح باگ در پلاگین**:
بعد کد نویسی و اجرای برنامه یک ارور میده و فایل build.config که کلید تپسل رو در اون تعریف  کردم به صورت خودکار حذف میشه نمیدونم مشکلش چیه و عکس ارور رو هم اینجا میزارم 
![tapsellone](https://user-images.githubusercontent.com/104717609/195993390-80c06767-a55b-450a-a810-c3c71cccedd0.JPG)
![tapseeltwo](https://user-images.githubusercontent.com/104717609/195993403-b2bf3191-cc70-468c-92e9-cdc00b3389cb.JPG)

generated source file should not be edited .the change will be lost when source are regenerated
خطایی که میده رو بالا نوشتم که بعد از اجرا تغییرات رو حذف میکنه 

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by mahdi-malv** [comment]
سلام
فایل buildconfig توسط دولپر ساخته نمیشه و auto generated هست
اینطوری توش دیتا بذارید:
https://stackoverflow.com/questions/51373523/change-buildconfig-file-in-android-studio-using-gradle

**Comment by 75q399996666n** [comment]
خیلی ممنون از پاسختون لینک رو بررسی میکنم
