### ISSUE TITLE
🐛  باگ: نشان ندادن تبلیغ زمان اجرای برنامه 

### ISSUE THREAD

**Issue by 75q399996666n** [tapsellorg/TapsellPlusSDK-AndroidSample#57]
<div dir='rtl'>

**شرح باگ در پلاگین**: طبق مستندات تپسل پیش رفتم و کد هارو به درستی نوشتم اما موقع اجرای برنامه فقط یک صفحه سفید بدون تبلیغ باز میشه و در ارور هم مینویسه که شناسه تبلیغ ناشناسه و ریسپانس مقدار null رو برمیگردونه 
عکس ارور رو پایین میزارم اگر میدونید مشکلش چیه ممنون میشم راهنمایی کنید 

![tappzonerror](https://user-images.githubusercontent.com/104717609/196775480-06e26488-e264-47da-b704-e2536acf9740.JPG)

اگر کافی نیست عکس کد هارو هم میزارم

**Comment by MortezaNedaei** [comment]
سلام. این خطا زمانی اتفاق میوفته که آی دی اشتباهی رو موقع درخواست تبلیغ استفاده کرده باشید.
مشکلی از بابت پیاده سازی وجود نداره. لطفا برای دریافت آی دی صحیح با کارشناسان پشتیبانی تماس بگیرید.
