### ISSUE TITLE
🐛  باگ: سپر امنیت بازار آنتی ویروس FSecure تپسل رو بدافزار تشخیص میده

### ISSUE THREAD

**Issue by versustech4** [tapsellorg/TapsellPlusSDK-AndroidSample#59]
<div dir='rtl'>

امروز کافه بازار برای اپلیکیشن هام اخطار داده و گفته سپر امنیت بازار و آنتی ویروس FSecure برنامه هام که توش از تپسل پلاس استفاده میکردم رو بدافزار تشخیص داده. 
تست کردم دیدم دقیقا وقتی کتابخونه تپسل پلاس 2.1.7 (آخرین نسخه) رو از پروژه حذف میکنم آنتی ویروس میگه اپ اوکیه و دقیقا وقتی تپسل رو به dependencies اضافه میکنم (فقط اضافه میکنم، حتی تبلیغیم نمایش نمیدم) آنتی ویروس میگه اپلیکیشن کلا بدافزاره.

</div>

**Comment by miladcoder** [comment]
سلام و عرض ادب
تکلیف این باگ چیشه ؟ حل شده تو نسخه جدید یا نه ؟ 
اینقدر بیخیال بودن هم صحیح نیست جناب پشتیبان !!

**Comment by MortezaNedaei** [comment]
سلام
- نسخه آخر تپسل با همین سمپل و با آنتی ویروس FSecure و VirusTotal تست شده و آسیب پذیری از طرف این سرویس ها گزارش نشده.
- شما هم میتونید یک apk از سمپل بگیرید و با FSecure تست کنید
- در صورتیکه شما هم هیچ آسیب پذیری از این پروژه نمیگیرید، احتمالا مشکل مربوط به کتابخانه های دیگه داخل پروژه‌تون باشه.
- اما در حالتیکه آسیب پذیری خاصی در همین پروژه مشاهده کردید، لطفا برامون ارسال کنید.

**Comment by MortezaNedaei** [comment]
در صورت یافتن مستنداتی از وجود این مشکل در کتابخانه، مجددا این issue را باز کنید
