### ISSUE TITLE
Attempt to invoke virtual method 'void ir.tapsell.plus.CacheObject.win(ir.tapsell.plus.model.AdNetworkEnum)' on a null object reference

### ISSUE THREAD

**Issue by abdollahammail** [tapsellorg/TapsellPlusSDK-AndroidSample#6]
سلام
گاهی برای نمایش بنر نیتیو با ارور زیر مواجه میشم که چون دقیقا برام واضح نبود مشکل از کجاست ممنون میشم راهنمایی کنید، اگر هم نیاز به دیدن کد هست که بفرمایید قرار بدم.
java.lang.NullPointerException: Attempt to invoke virtual method 'void ir.tapsell.plus.CacheObject.win(ir.tapsell.plus.model.AdNetworkEnum)' on a null object reference
        at ir.tapsell.plus.a.a(CacheManager.java:46)
        at ir.tapsell.plus.q.b(ShowManager.java:239)
        at ir.tapsell.plus.q.a(ShowManager.java:154)
        at ir.tapsell.plus.q.c(ShowManager.java:98)
        at ir.tapsell.plus.q.a(ShowManager.java:41)
        at ir.tapsell.plus.q.a(ShowManager.java:50)
        at ir.tapsell.plus.u.a(TapsellPlusController.java:205)
        at ir.tapsell.plus.TapsellPlus.showAd(TapsellPlus.java:106)

**Comment by behdad222** [comment]
از نسخه چند تپسل استفاده میکنید؟

**Comment by abdollahammail** [comment]
1.0.8-beta

**Comment by behdad222** [comment]
شنبه بررسی میکنم

**Comment by abdollahammail** [comment]
بهدادجان فرصت شد مشکل رو یررسی کنید؟

**Comment by behdad222** [comment]
@abdollahammail لطفا کد زمان درخواست تبلیغ و زمان نمایش رو بفرستید

**Comment by abdollahammail** [comment]
درخواست تبلیغ در فرگمنت و آپدیت آداپتر:
```
TapsellPlus.requestNativeBanner(getActivity(), Constants.AD_TEST_KEY_ADMOB_NATIVE, new AdRequestCallback() {
        @Override
        public void response(String adId) {
            StoriesRow storiesRow = new StoriesRow(null, true, adId);
            items.add(index, storiesRow);
            adapter.updateStoryItems(items);
        }

        @Override
        public void error(String s) {
        }
    });
```

ایجاد ویو هولدر برای تبلیغ:
```
@Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        if (viewType == ITEM_TYPE_AD) {
            return new AdViewHolder(LayoutInflater.from(context).inflate(R.layout.ad_container, parent, false), context);
        }
        ...
    }
```

بایند کردن:
```
@Override
public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        if (getItemViewType(position) == ITEM_TYPE_AD) {
            AdViewHolder adViewHolder = (AdViewHolder) holder;
            if (adViewHolder != null)
                adViewHolder.bindView(position);
        } else {
	....
        }
    }
```

کلاس ویو هولدر مربوط به تبلیغ:
```
public class AdViewHolder extends RecyclerView.ViewHolder {

        private FrameLayout adContainer;
        private AdHolder adHolder;
        private Activity activity;


        private AdViewHolder(View view, Activity activity) {
            super(view);
            this.activity = activity;
            adContainer = view.findViewById(R.id.adContainer);
            adHolder = TapsellPlus.createAdHolder(activity, adContainer, R.layout.ad_list_native);
        }

        private void bindView(int position) {
            String adId = "";
            if (filteredItems.get(position) != null)
                adId = filteredItems.get(position).getAdId();
            TapsellPlus.showAd(activity, adHolder, Constants.AD_TEST_KEY_ADMOB_NATIVE, adId, new AdShowListener() {
                @Override
                public void onOpened() {
                    super.onOpened();
                }

                @Override
                public void onClosed() {
                    super.onClosed();
                }

                @Override
                public void onRewarded() {
                    super.onRewarded();
                }

                @Override
                public void onError(String s) {
                    super.onError(s);
                }
            });
        }
    }
```

**Comment by behdad222** [comment]
مقدار adId زمان نمایش چی هست؟
موقع صدا زدن showAd

**Comment by abdollahammail** [comment]
مقدارش همون اد‌آیدی هست که توی ریکوئست‌نیتیو‌بنر از تپسل گرفتم و پاس داده شده به آداپتر.

**Comment by behdad222** [comment]
میشه لاگ کنیدش و یه نمونه رو برام بفرستید

**Comment by abdollahammail** [comment]
دوبار لاگ کردم.
دفعه‌ی اول ۵۷ و دفعه‌ی دوم ۱۳۱.

البته ارور مربوط به اون نمیتونه باشه چون الان تست کردم و به جای ادآیدی توی شوبنر مقدار نال و استرینگ خالی هم فرستادم و تبلیغ نمایش داده شد و به ارور نخورد.

این رو هم بگم که این کرش دائمی نیست، از هر ۱۰ بار اجرا شاید فقط ۴-۵ بار با این مشکل مواجه بشه.

**Comment by behdad222** [comment]
در صورتی که `adId` مقدار اشتباهی باشه این کرش رخ میده
مثلا من به شما  `"12"` بدم و شما یه مقدار دیگه

تو پیاده سازی اشتباهی نداشتید؟
مثلا `position` اشتباهی رو گرفته 

`filteredItems`
لیست فیلتر شده هست؟
تو فیلتر کردن ممکن نیست اشتباهی رخ داده باشه؟

**Comment by abdollahammail** [comment]
آخه من با adId خالی هم تست کردم و مشکلی پیش نیومد.

نه مطمئنا لیست درسته، چون اگر غلط بود اساسا اون آیتم نمیتونست تبلیغ باشه و یکی از آیتم‌های خود لیست(که تبلیغ نیست) برنامه برمیگشت که مقدار اد‌آیدیش خالیه.

**Comment by behdad222** [comment]
خالی بودنش چک میشه ولی اشتباه بودنش باعث کرش میشه
خودتون میتونید کرش رو ایجاد کنید مثلا `adid` رو با یه چیز دیه `concat` کنید

**Comment by abdollahammail** [comment]
بله اتفاقا الان همین کار رو کردم و کرش کرد.
عجیبه نمیدونم چرا همچین اتفاقی رخ میده، بررسی میکنم دوباره.
ممنونم از وقتی که گذاشتی.
