### ISSUE TITLE
🚀[فیچر]: kotlin و compose

### ISSUE THREAD

**Issue by mz4reall** [tapsellorg/TapsellPlusSDK-AndroidSample#61]
<div dir='rtl'>

سلام ، ایا برنامه ایی برای پشتیبانی از kotlin و compose در آینده دارین؟

</div>

**Comment by MortezaNedaei** [comment]
سلام، بله از [پروژه نمونه کامپوز](https://github.com/tapsellorg/TapsellPlusSDK-Jetpack-Compose-Sample) استفاده کنید
