### ISSUE TITLE
🐛 [BUG/ERROR] Adding TapsellPlusSDK to the project somehow disables R8 (minify and shrink) project wide

### ISSUE THREAD

**Issue by yamin8000** [tapsellorg/TapsellPlusSDK-AndroidSample#63]
I don't know why but adding this library to the project somehow disables apk size shrinking which is very frustrating considering it causes us indirectly to make a simple 2 MB app to a whopping 8 MB for no reason whatsoever.
I know this library uses multiple ad services and is bound to its limits but it's very unreasonable and even amateur for a simple ad library to add 6 MB to the project size.
If this library was open-source end users could fork their version and reduce the size or at least if you want to keep it closed source I suggest making it modular so if I only want to use one of the services I only add the dependency and that desired ad service module.

related: #49 #7

**Comment by MortezaNedaei** [comment]
Can you give it a try with `2.2.4`? Don't forget to add `android.enableR8.fullMode=true` in your gradle.properties

**Comment by yamin8000** [comment]
> Sorry for the delay. Can you give it a try with `2.2.4`? Don't forget to add `android.enableR8.fullMode=true` in your gradle.properties

I already abandoned that project that used Tapsell, I'll try next time I need to use Tapsell.
