### ISSUE TITLE
🐛  باگ: Failed to connect to plus.tapsell.ir/0.0.0.0:443

### ISSUE THREAD

**Issue by miladcoder** [tapsellorg/TapsellPlusSDK-AndroidSample#65]
<div dir='rtl'>

**شرح باگ در پلاگین**:

همانطور که در جریان هستین در حال حاظر حدود 90 درصد کاربران با vpn به برنامه ها دسترسی دارند و برنامه من هم اینطور هست که کاربران برای استفاده نیاز به vpn دارند
در زمان لود تبلیغات با خطای 443 مواجه میشم و این فقط زمانی رخ میدهد که کاربر با vpn وارد برنامه شود . در صورتی که vpn غیرفعال باشد تبلیغات با موفقیت لود میشوند . 
لطفا راهنمایی بفرمایید این مشکل را به چه صورت میتوان مرتفع نمود

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

E/TAP_SDK_WaterfallManag: onWaterfallFailed: Failed to connect to plus.tapsell.ir/0.0.0.0:443

</div>

**Comment by MortezaNedaei** [comment]
این مشکل زمانی اتفاق میوفته که اپ نتونه به سرور های تپسل متصل بشه و مشکل مربوط به VPN مورد استفاده هست و با کتابخانه تپسل ارتباطی نداره. لطفا با یک VPN دیگه تست کنید
