### ISSUE TITLE
چند مشکل کتابخانه تپسل پلاس

### ISSUE THREAD

**Issue by hossinasaadi** [tapsellorg/TapsellPlusSDK-AndroidSample#7]
سلام 
توی پیاده سازی بامشکلات زیادی روبه رو شدم که بعضی از اون ها باعث شد یک سری از کتابخانه های مورد نیاز دستکاری کنم
و قابلیت مینیفای با اضافه کردن این کتابخانه به مشکل بر میخورد.
مورد بعدی اگر بخواهیم از یکی یا چند تبلیغ دهنده دلخواه استفاده کنیم در هنگام اجرا ،اپلیکیشن کرش میشه که دلیل اضافه نکردن کتابخانه دیگر تبلیغ دهنده هاست . 
درضمن حجم این کتابخانه ها خیلی زیاده و باعث میشه یک اپلیکیشن
 1.5MB
 به 
4.7MB
 برسه
 بنظرم این ها مشکلاتی بود که باید حل بشه
تشکر

**Comment by behdad222** [comment]
به چه مشکلی خوردید و به چه صورتی دست کاری کردید؟

چه کرشی میکنه و از نسخه چند تپسل استفاده میکنید؟
