### ISSUE TITLE
🐛 Tapsell Plus is not Initialized error in release variants

### ISSUE THREAD

**Issue by arbabi1368** [tapsellorg/TapsellPlusSDK-AndroidSample#70]
<div dir='rtl'>

سلام
بنده در اپ اندرویدی تپسل پلاس را پیاده سازی کردم و در نسخه debug با موفقیت نمایش تبلیغ را مشاهده میکنم. ولی وقتی برنامه را برای انتشار نسخه release آن را میسازم تبلیغ نمایش داده نمیشود.
مشکل  هنگام استفاده از پروگارد و فایل proguard_rules.pro هست ولی طبق مستندات پیش رفتم و دستورات لازم به به این فایل اضافه کردم  ولی فایده نداشت.
موقع ریلیز با proguard  خطای  Tapsell Plus is not Initialized!  میده
لطفا راهنمایی بفرمایید، باتشکر.

</div>

**Comment by MortezaNedaei** [comment]
سلام، لازمه چند مورد رو بررسی کنید:
- درصورتیکه در پروژه از android.enableR8.fullMode=true استفاده می‌کنید، فعلا لازمه غیر فعالش کنید تا پشتیبانیش اضافه بشه.
- اما در صورتیکه از r8 full mode استفاده نمی‌کنید، احتمالا مشکل از کتابخانه های دیگه داخل پروژه‌تون باشه و ممکنه rule های پروگاردشون به درستی اضافه نشده باشه و در عملکرد تپسل اختلال ایجاد کنه. پس کتابخانه تپسل رو در یک پروژه تستی بدون کتابخانه های دیگه (مثل سمپل) اضافه کنید و ببینید مشکل مربوط به کدوم کتابخانه هست؟ (میتونید پروژه تستی خودتون رو برامون آپلود کنید تا بررسی کنیم)
- همچنین لطفا از همین سمپل یک ریلیز apk بگیرید. نباید مشکلی وجود داشته باشه

**Comment by MortezaNedaei** [comment]
لطف کنید مورد ۲ و ۳ کامنت بالا رو انجام بدین
یه پروژه تستی بفرستین که مشکل رو بررسی کنیم.

**Comment by MortezaNedaei** [comment]
سلام. این مشکل در نسخه `2.2.4` حل شده و با گریدل نسخه `8.2.0` هم تست شد. [لینک اپ سمپل](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample)
در این نسخه میتونید از `R8 Full Mode` هم مطابق کد زیر استفاده کنید
`android.enableR8.fullMode=true`
