### ISSUE TITLE
🐛  باگ: resource not exist

### ISSUE THREAD

**Issue by AmirSinaRZ** [tapsellorg/TapsellPlusSDK-AndroidSample#72]
<div dir='rtl'>

سلام،
می‌دونم چرا در هیچکدام از تبلیغات عکسی وجود نداره مثلا داخل تبلیغات جایزه ای عکس قطع صدا/صدا وجود نداره و فقط یک مربع خاکستری نمایش داده میشه

</div>

**Comment by MortezaNedaei** [comment]
سلام، 
یک اسکرین شات میفرستید که مشکلش رو ببینم.
روی کلید سمپل هم همین مشکل وجود داره؟

**Comment by AmirSinaRZ** [comment]
![Screenshot_2023-08-14-13-11-52-138_com sina tapsell](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/assets/116455534/f8da0564-efcb-4649-9db7-43f5652b3b52)
بله رو سمپل هم این مشکل هست
کلا فکر کنم assets ناقص دانلود میشه نمیشه ضمیمه کنید assets تپسل رو؟

**Comment by MortezaNedaei** [comment]
لطفا یکبار clear data  کنید و مجدد تست کنید

**Comment by AmirSinaRZ** [comment]
متاسفانه مشکل حل نشد

**Comment by MortezaNedaei** [comment]
روی تست من این مشکل وجود نداره. 
لطفا روی یه موبایل دیگه هم تست کنید تا بتونیم تشخیص بدیم که مشکل مربوط به نوع خاصی از موبایل هست یا خیر.
ممنون

**Comment by AmirSinaRZ** [comment]
امکانش هست شما خروجی سمپل رو اینجا ضمیمه کنید ؟

**Comment by MortezaNedaei** [comment]
لطفا این رو تست کنید
[app-universal-release.apk.zip](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/files/12335544/app-universal-release.apk.zip)

**Comment by MortezaNedaei** [comment]
لطفا این لینک رو تست کنید
[app-universal-release.apk.zip](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/files/12336026/app-universal-release.apk.zip)

**Comment by MortezaNedaei** [comment]
در کامنت بالا اضافه کردم. هر دو حالتش مشکلی نداره.

**Comment by AmirSinaRZ** [comment]
فکر کنم بخاطر resource ها این مشکل پیش میاد خروجی هایی که شما ارسال کردید resource ها confuse شدن . میخواستم ببینم اگر این کار رو نکنید باز هم این مشکل پیش میاد یا نه.
من این کار رو نکردم و مشکل حل شد. ممنون از پاسخگویی
