### ISSUE TITLE
Tapsell Resources

### ISSUE THREAD

**Issue by AmirSinaRZ** [tapsellorg/TapsellPlusSDK-AndroidSample#73]
سلام ، من هرموقع از تپسل استفاده میکنم هیچ resource وجود ندارد یعنی اصلا کلا دانلود نمیشه، راهی هست که بتونم پوشه res رو داشته باشم؟

**Comment by MortezaNedaei** [comment]
سلام. ریسورس های تپسل، در بخش `External Libraries` پروژه قابل مشاهده هستن.
مشکل دقیقا چی هست؟
این آیدی ساپورت تلگرام هست. اگه لازمه توضیح شفاف تری بدید، اینجا میتونید پیام بدید
`@TapsellTechSupport`

**Comment by AmirSinaRZ** [comment]
من نمیتونم بهشون دسترسی داشته باشم امکانش هست attach کنید

**Comment by MortezaNedaei** [comment]
داخل اندروید استودیو، بخش External Libraries قابل مشاهده هستن.
دقیقا چکار میخواید بکنید؟ 
![Screenshot 2023-08-20 at 10 14 59 AM](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/assets/38072572/b235a09d-c11b-4538-9d40-6d872e744d2f)

**Comment by AmirSinaRZ** [comment]
درست ، ولی پس چرا هنگام استفاده از تبلیغات Pre-Roll ارور resource not found رخ میده؟
R$layout داخل

**Comment by MortezaNedaei** [comment]
در مرحله اول چک کنید ببینید این ارور از سمت کلاس های تپسل برمیگرده؟
زمانی که درخواست تبلیغ میزنید، کل لاگی که در لاگکت میگیرید رو بفرستید چک کنم.
 سعی کنید اطلاعات رو یکجا و به صورت کامل بفرستید تا بتونیم سریعتر مشکلتون رو بررسی کنیم.

**Comment by AmirSinaRZ** [comment]
بله بفرمایید
```
08-20 21:47:14.650 11637 11637 E AndroidRuntime: Process: ir.tapsell.plussample.android, PID: 11637

08-20 21:47:14.650 11637 11637 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.tapsell.plussample.android/ir.tapsell.plussample.android.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d00a4

08-20 21:47:14.650 11637 11637 E AndroidRuntime: 	at ir.tapsell.sdk.preroll.TapsellPrerollAd.addTapsellContainer(Unknown Source:14)

08-20 21:47:14.650 11637 11637 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:537)

08-20 21:47:28.653 11867 11908 E TAP_SDK_: Tapsell SDK is outdated! Latest version is 4.8.1. Please update.

```

**Comment by MortezaNedaei** [comment]
شما باید ویوگروپی که ویدیوپلیرتون داخلش هست و تبلیغ قراره روش نمایش داده بشه رو با متود `setAdContainer` بفرستید برای تپسل.
مثال نحوه درست استفاده در [این لینک](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/blob/master/app/src/main/java/ir/tapsell/plussample/android/ExoPlayerVastActivity.java#L114) هست
