### ISSUE TITLE
🐛  باگ: اجرای اپ که تپسل پلاس بهش اضافه شده

### ISSUE THREAD

**Issue by ahzab110** [tapsellorg/TapsellPlusSDK-AndroidSample#74]
<div dir='rtl'>

**شرح باگ در پلاگین**:

سلام 
یه گیم اندروید امشب خروجی گرفتم

با شبیه ساز بلواستکس بالا میاد بدون مشکل و سالم 

ولی تو موبایل بازش میکنم بسته میشه بصورت خودکار

تبلیغات تپسل هم داره 

قبلا بدون تپسل خروجی اجرا میشد الان نمیشه

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
سلام
- فایل apkش رو بفرستید یا لاگی که موقع کرش میگیرید رو ارسال کنید بررسی کنیم.
- پروژه رو با یونیتی زدین؟

**Comment by MortezaNedaei** [comment]
من این ایشو رو میبندم. در صورت عدم رفع مشکل، مجدد باز کنید.
