### ISSUE TITLE
🐛  Release Initialization problem on Gradle 8

### ISSUE THREAD

**Issue by mz4real** [tapsellorg/TapsellPlusSDK-AndroidSample#75]
<div dir='rtl'>
سلام
وقتی ریلیز میگیرم تپسل initialize نمیکنه اما وقتی که shrinkResources true و minifyEnabled true رو غیر فعالسازیی میکنم کار میکنه پروگاردو از اینجا  https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/blob/master/app/proguard-rules.pro کپی کردم اما فایده ایی نداشت.
کد initialize :

        TapsellPlus.initialize(this, "key",
                new TapsellPlusInitListener() {
                    @Override
                    public void onInitializeSuccess(AdNetworks adNetworks) {
                        Log.e("tapsell", "onInitializeSuccess :::::" + adNetworks.name());
                    }

                    @Override
                    public void onInitializeFailed(AdNetworks adNetworks,
                                                   AdNetworkError adNetworkError) {
                        Log.e("tapsell", "ad network: " + adNetworks.name() + ", error: " + adNetworkError.getErrorMessage());
                    }
                });
        TapsellPlus.setGDPRConsent(this, true);

نسخه های کتابخونه ها:
    //tapsell
    implementation 'ir.tapsell.plus:tapsell-plus-sdk-android:2.2.0'

    //admob
    implementation 'com.google.android.gms:play-services-ads:22.1.0'

</div>

**Comment by mz4real** [comment]
-keep class ir.tapsell.plus.** { *; }
-keep class ir.tapsell.sdk.** { *; }

اینارو ادد کردم که tapsell proguard اثر نکنه روشون ولی کسی راه حلی بهتریی داره ؟

**Comment by mz4real** [comment]
خب بعد از کلی اعصاب خورد کنی ، گریدل ورژن رو از 8 اوردم روی 7.2.1 درست شد 
واقعا نمیدونم چه ربطی داره ولی درست شد برام 
vpn ام خوبه مشکلی نداره

عکس هم گذاشتم براتون :)


![Screenshot 2023-09-15 170233](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/assets/110531444/15af603a-cd15-4152-8906-3d42ae1f10b2)

امتحان کنین ببینین فقط مشکل من ایتجوریه ؟

**Comment by MortezaNedaei** [comment]
سلام روز بخیر، اینکه در حالت ریلیز کار نمیکنه، چند تا دلیل میتونه داشته باشه:
  
- درصورتیکه در پروژه از android.enableR8.fullMode=true استفاده می‌کنید، فعلا لازمه مقدارش رو false کنید تا پشتیبانیش در آینده اضافه بشه (در گریدل ۸ باید به صورت پیش‌فرض باید فعال )
 
- اما در صورتیکه از r8 fullMode استفاده نمی‌کنید، احتمالا مشکل از کتابخانه های دیگه داخل پروژه‌تون باشه و ممکنه rule های پروگاردشون به درستی اضافه نشده باشه و در عملکرد تپسل اختلال ایجاد کنه.
- برای حالت دوم لازمه کتابخانه تپسل رو در یک پروژه تستی بدون کتابخانه های دیگه (مثل سمپل) اضافه کنید و ببینید مشکل مربوط به کدوم کتابخانه هست؟ (میتونید پروژه تستی خودتون رو هم برامون آپلود کنید تا بررسی کنیم)

**Comment by MortezaNedaei** [comment]
سلام. این مشکل در نسخه `2.2.4` حل شده و با گریدل نسخه 8.2.0 هم تست شد. [لینک اپ سمپل](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample)
 در این نسخه میتونید از R8 Full Mode هم مطابق کد زیر استفاده کنید
`android.enableR8.fullMode=true`

لینک سمپل
