### ISSUE TITLE
Show Admob ads with Iran’s ip?

### ISSUE THREAD

**Issue by mz4real** [tapsellorg/TapsellPlusSDK-AndroidSample#78]
<div dir='rtl'>

**سلام  من مدتی هست که از درامد دلاری استفاده میکنم ، اما نمایش تبلیغات دلاری با ip ایرانی خیلی خیلی کم اتفاق میفته و وقتی فیلتر شکن روشن میکنم درست میشه دلیلش چیه یعنی ip ایرانی محدود هستش ؟ یا چون تپسل واسطه هستش ؟ چون بقیه برنامه هایی که بصورت مستقیم از ادموب استفاده میکنن خیلی سریع تبلیغات ادموب چه خارجی و چه ایرانی لود میشن اونم با ip  ایرانی . 
</div>

**Comment by MortezaNedaei** [comment]
بله در حال حاضر استفاده از بعضی تبلیغات خارجی مثل ادموب با ip ایران ممکن نیست و لازمه از VPN برای فعال سازی کتابخانه و درخواست تبلیغ استفاده کنید.
این مورد ارتباطی با کتابخانه تپسل‌پلاس نداره
