### ISSUE TITLE
🐛  باگ:   کرش بازی یونیتی اندروید هنگام اجرا با اضافه شدن تپسل پلاس

### ISSUE THREAD

**Issue by amirJM123** [tapsellorg/TapsellPlusSDK-AndroidSample#83]
سلام بنده نیاز به کمک دارم ، در یونیتی تپسل پلاس را اضاف کردم اما پس از خروجی اندروید که شامل پکیج تپسل پلاس است ، پس از اجرای آن روی هر گوشی اندروید (کرش میکند و در کسری از ثانیه من رو بیرون می انداره) و با حذف کامل پیکیج تپسل پلاس درست میشه ، لطفا کمک کنید چطور این مشکل را حل کنم که تبلیغ تپسل در پروزه باشه اما کرش نکنه. 

نکته هیچ خطایی دریافت نمیکنم و بیلد انجام میشه اما در اجرا کرش میکند.

**Comment by MortezaNedaei** [comment]
سلام. 
کتابخانه تپسل از کتابخانه Google Mobile Ads به عنوان وابستگی داخلی استفاده می‌کند. در صورتیکه با این خطا مواجه شدید، لازم است وارد مسیر `Assets/Google Mobile Ads` شده و اپ آیدی مورد نیاز اندروید را در آن وارد نمایید. در صورتی که از ادموب استفاده نمیکنید، میتوانید از اپ آیدی تست ادموب (`ca-app-pub-3940256099942544~3347511713`) استفاده کنید. در غیر اینصورت اپ آیدی اختصاصی خود را وارد نمایید.

![image](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/assets/38072572/fc43cd76-b644-4e74-8445-3b8ff0ac2538)

**Comment by amirJM123** [comment]
من همینکاری که گفتی رو انجام دادم ولی بازم خروجی میدم اجراش میکنم در کسری
از ثانیه کرش میکنه واقعا این مشکل راه حل نداره!؟

در تاریخ پنجشنبه ۲۲ فوریهٔ ۲۰۲۴،‏ ۲۲:۵۰ MoNe ***@***.***>
نوشت:

**Comment by MortezaNedaei** [comment]
پکیج Android Logcat رو مطابق [این لینک](https://docs.tapsell.ir/faq/plus-sdk/unity/#%DA%AF%D8%B1%D9%81%D8%AA%D9%86-%D9%84%D8%A7%DA%AF-%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF) نصب کنید و لاگ نیتیو اندروید که در زمان کرش میگیرید رو بفرستید بررسی کنیم
