### ISSUE TITLE
با پروگارد فعال، کلاس ها رو پیدا نمیکنه

### ISSUE THREAD

**Issue by hadittt** [tapsellorg/TapsellPlusSDK-AndroidSample#85]
Missing class com.adcolony.sdk.*
Missing class com.chartboost.sdk.*
Missing class com.google.ads.*
....

چرا فایل پروگارد توی پروژه نمونه خالیه؟

**Comment by MortezaNedaei** [comment]
این مشکل در نسخه بعد حل میشه ولی فعلا از فایل `app/build/outputs/mapping/release/missing_rules.txt `، رول های موردنیاز رو کپی کنید و داخل فایل پروگارد پروژه قرار بدین.

**Comment by hadittt** [comment]
درست شد. خیلی ممنون که سریع پاسخ دادین ..❤️
