### ISSUE TITLE
نسخه جدید اندروید استودیو

### ISSUE THREAD

**Issue by xzmohammad** [tapsellorg/TapsellPlusSDK-AndroidSample#89]
<div dir='rtl'>

**شرح باگ در پلاگین**:
در بخش بیلد گریدل نسخه جدید اندروید استودیو این ها را اصلا نمیشه وارد کرد از کد خطا میگیره 
packagingOptions {
        resources.excludes.add("META-INF/*")
    }
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a' //select ABIs to build APKs for
            universalApk true //generate an additional APK that contains all the ABIs
        }
        signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    و یک سوال دیگه شما در پروژه نمونه compileSdk = 33 و targetSdk = 33 قرار دادید آیا روی 34 هم اوکیه تبلیغ پخش میشود؟ 
    من فقط میخواهم تبلیغ تپسلو راه بندازم ینمه آماتورم مو به مو آموزشارو رفتم باز هم به جایی نرسیدم (مشکلی از کد یا شناسه تبلیغ یا کلید تپسل نیست چندین بار چک کردم)

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
سلام. این سمپل با آخرین نسخه های اندروید استودیو تست شده و مشکلی روی نسخه جدید نداره. شما چه اروری میگیرید؟ 
البته این کد های بالا فقط برای بیلد ریلیز هستن و در صورتی که نیاز ندارید، میتونید حذف کنید

**Comment by xzmohammad** [comment]
حرف شما درست است 
مشکل این بود که من از کتابخانه 2.2.6 تپسل استفده میکردم و وقتی من و دوستانم به 2.2.5 آن را تغییر دادیم تبلیغ هم برای من و دوستانم نمایش داده شد و تبلیغ بنده آنی/جایزه ای بود 
از تیم پشتیبان تپسل و آقا مرتضی ممنونیم (ایموجی قلب)
