### ISSUE TITLE
🐛  باگ: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated

### ISSUE THREAD

**Issue by Eilya112** [tapsellorg/TapsellPlusSDK-AndroidSample#91]
**شرح باگ در پلاگین**: با فعال کردن R8 در این خطا بوجود می آید

**متن کامل خطا یا لاگ مرتبط به طور کامل**: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in C:\Users\eilya\AndroidStudioProjects\1.Kotlin\Note\app\build\outputs\mapping\release\missing_rules.txt.

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
- نسخه کتابخانه چند هست؟
- وارد مسیر `Note\app\build\outputs\mapping\release\missing_rules.txt` شده و محتویات موجود در فایل رو داخل فایل proguard خودتون کپی کنید

**Comment by Eilya112** [comment]
implementation 'ir.tapsell.plus:tapsell-plus-sdk-android:2.2.6'

**Comment by MortezaNedaei** [comment]
محتویات فایل `missing_rules.txt` رو هم لطفا بفرستید

**Comment by Eilya112** [comment]
داخل  missing_rules.txt این موارد هست
-dontwarn com.google.ads.mediation.admob.AdMobAdapter
-dontwarn com.google.android.ump.ConsentForm$OnConsentFormDismissedListener
-dontwarn com.google.android.ump.ConsentInformation$OnConsentInfoUpdateFailureListener
-dontwarn com.google.android.ump.ConsentInformation$OnConsentInfoUpdateSuccessListener
-dontwarn com.google.android.ump.ConsentInformation
-dontwarn com.google.android.ump.ConsentRequestParameters$Builder
-dontwarn com.google.android.ump.ConsentRequestParameters
-dontwarn com.google.android.ump.FormError
-dontwarn com.google.android.ump.UserMessagingPlatform

**Comment by MortezaNedaei** [comment]
این مواردی که نوشته مربوط به اضافه نکردن ادموب به پروژه هست.
در صورتیکه نمیخواین از ادموب استفاده کنید، همین موارد رو کپی کنید و داخل فایل `proguard-rules.pro` قرار بدید. 
ولی در صورتیکه بعدا خواستید ادموب رو به پروژه اضافه کنید، نیازی به استفاده از این رول ها داخل پروگارد نیست

**Comment by Eilya112** [comment]
اضافه کردم ولی خطا میگیره باسید تغییری درش ایجاد کنم
![Uploading 2.PNG…]()

**Comment by MortezaNedaei** [comment]
عکستون درست آپلود نشده. بمونید تا آپلود بشه و بعد بفرستید

**Comment by Eilya112** [comment]
![2](https://github.com/tapsellorg/TapsellPlusSDK-AndroidSample/assets/90218996/e8b15261-8b81-4235-8b0a-488b97652f2a)

**Comment by Eilya112** [comment]
بجای dontwarn  از keep استفاده کردم  ولی اینبار $  رو خطا میگیره

**Comment by MortezaNedaei** [comment]
الآن مجدد بیلد کنید و ببینید چه خطایی هست؟

**Comment by Eilya112** [comment]
تشکر فراوان از شما دوست عزیز 
حل شد 
ممنونم

**Comment by MortezaNedaei** [comment]
خواهش میکنم.
در نسخه های بعدی این مورد رو داخل کتابخانه مدیریت میکنیم
همچنین برای ساده تر شدن، میتونید از رول زیر به جای موارد بالا استفاده کنید:
`-dontwarn com.google.**`
