### ISSUE TITLE
مشکل در راه اندازی 🐛  باگ: 

### ISSUE THREAD

**Issue by AmirSinaRZ** [tapsellorg/TapsellPlusSDK-AndroidSample#92]
**شرح باگ در پلاگین**:
راه اندازی تپسل پلاس انجام نمیشه یا 
```
TapsellPlus.initialize(this, TapsellKey,
				new TapsellPlusInitListener() {
	            @Override
	            public void onInitializeSuccess(AdNetworks adNetworks) {
		                Log.d("onInitializeSuccess", adNetworks.name());
		            }
	
	            @Override
	            public void onInitializeFailed(AdNetworks adNetworks,
							AdNetworkError adNetworkError) {
		                Log.e("onInitializeFailed", "ad network: " + adNetworks.name() + ", error: " +	adNetworkError.getErrorMessage());
		            }
	        });
```

اصلا اجرا نمیشه

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
```
08-01 06:41:19.166  6880  6880 E LOCStat : in init time: UNKNOWN_LOCATION
08-01 06:41:19.165  6880  6880 E GDSoverall: in init time: false
```

**Comment by MortezaNedaei** [comment]
از چه ‌ورژنی استفاده می‌کنید؟ به ورژن آخر آپدیت کنید و مجدد تست کنید

**Comment by AmirSinaRZ** [comment]
```ir.tapsell.plus:tapsell-plus-sdk-android:2.2.6```

**Comment by MortezaNedaei** [comment]
این مشکل رو میتونید در همین سمپلی که قرار دادیم، تولید کنید؟

**Comment by AmirSinaRZ** [comment]
این مشکل رو با سمپل دارم

**Comment by MortezaNedaei** [comment]
این مشکل در حال بررسی هست.
آیا در لود کردن تبلیغات هم مشکل دارید؟

**Comment by AmirSinaRZ** [comment]
نه مشکلی نداره

**Comment by MortezaNedaei** [comment]
من یک فایل apk از همین سمپل اینجا فرستادم و یک toast هم گذاشتم که موقع initialize شدن باید بهتون نشون داده بشه. من تست کردم init میشه. لطفا شما هم تست کنید

[tapsell-plus-2.2.6-release.apk.zip](https://github.com/user-attachments/files/16581365/tapsell-plus-2.2.6-release.apk.zip)

**Comment by AmirSinaRZ** [comment]
ورژن کتابخونه gms رو تغییر دادم الان init میشه

**Comment by MortezaNedaei** [comment]
کتابخانه تپسل از نسخه `22.6.0` ادموب استفاده میکنه
