### ISSUE TITLE
🐛  باگ: مشکل نامشخص در کتابخانه

### ISSUE THREAD

**Issue by syedmohdbarzgar** [tapsellorg/TapsellPlusSDK-AndroidSample#99]
<div dir='rtl'>

**شرح باگ در پلاگین**:
نسخه sdk 2.2.8 یک خطا که از اجرای برنامه در زمان build بوجود می اید

**متن کامل خطا یا لاگ مرتبط به طور کامل**:
ContentVideoAdTemplateBinding.java:16: error: package ir.tapsell.sdk.nativeads.views.videoplayer does not exist
import ir.tapsell.sdk.nativeads.views.videoplayer.VideoContainer;
                                                 ^

ContentVideoAdTemplateBinding.java:45
: error: cannot find symbol
  public final VideoContainer tapsellNativeadVideo;
               ^
  symbol:   class VideoContainer
  location: class ContentVideoAdTemplateBinding

ContentVideoAdTemplateBinding.java:51: error: cannot find symbol
      @NonNull VideoContainer tapsellNativeadVideo) {
               ^
  symbol:   class VideoContainer
  location: class ContentVideoAdTemplateBinding
***************************************************
AppInstallationVideoAdTemplateBinding.java:16: error: package ir.tapsell.sdk.nativeads.views does not exist
import ir.tapsell.sdk.nativeads.views.RateStarView;
                                     ^
AppInstallationVideoAdTemplateBinding.java:17: error: package ir.tapsell.sdk.nativeads.views.videoplayer does not exist
import ir.tapsell.sdk.nativeads.views.videoplayer.VideoContainer;
                                                 ^

AppInstallationVideoAdTemplateBinding.java:40: error: cannot find symbol
  public final RateStarView tapsellNativeadRating;
               ^
  symbol:   class RateStarView
  location: class AppInstallationVideoAdTemplateBinding

AppInstallationVideoAdTemplateBinding.java:49: error: cannot find symbol
  public final VideoContainer tapsellNativeadVideo;
               ^
  symbol:   class VideoContainer
  location: class AppInstallationVideoAdTemplateBinding

AppInstallationVideoAdTemplateBinding.java:54: error: cannot find symbol
      @NonNull RateStarView tapsellNativeadRating, @NonNull TextView tapsellNativeadSponsored,
               ^
  symbol:   class RateStarView
  location: class AppInstallationVideoAdTemplateBinding

AppInstallationVideoAdTemplateBinding.java:55: error: cannot find symbol
      @NonNull TextView tapsellNativeadTitle, @NonNull VideoContainer tapsellNativeadVideo) {
                                                       ^
  symbol:   class VideoContainer
  location: class AppInstallationVideoAdTemplateBinding
**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
- این مشکل رو در اپ سمپل هم تونستید ببینید؟
- پیاده سازیتون مطابق پروژه سمپل هست؟

**Comment by syedmohdbarzgar** [comment]
همه چیز مطابق مستندات است

**Comment by syedmohdbarzgar** [comment]
کلاس ها وجود دارند اما زمان اجرا خطا میدهد و به این صفحه میرود 
// Generated by view binder compiler. Do not edit!
package org.token.tracking.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.card.MaterialCardView;
import ir.tapsell.sdk.nativeads.views.RateStarView;
import ir.tapsell.sdk.nativeads.views.videoplayer.VideoContainer;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.token.tracking.R;

public final class AppInstallationVideoAdTemplateBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final LinearLayout rvHeader;

  @NonNull
  public final Button tapsellNativeadCta;

  @NonNull
  public final TextView tapsellNativeadDescription;

  @NonNull
  public final ImageView tapsellNativeadLogo;

  @NonNull
  public final RateStarView tapsellNativeadRating;

  @NonNull
  public final TextView tapsellNativeadSponsored;

  @NonNull
  public final TextView tapsellNativeadTitle;

  @NonNull
  public final VideoContainer tapsellNativeadVideo;

  private AppInstallationVideoAdTemplateBinding(@NonNull MaterialCardView rootView,
      @NonNull LinearLayout rvHeader, @NonNull Button tapsellNativeadCta,
      @NonNull TextView tapsellNativeadDescription, @NonNull ImageView tapsellNativeadLogo,
      @NonNull RateStarView tapsellNativeadRating, @NonNull TextView tapsellNativeadSponsored,
      @NonNull TextView tapsellNativeadTitle, @NonNull VideoContainer tapsellNativeadVideo) {
    this.rootView = rootView;
    this.rvHeader = rvHeader;
    this.tapsellNativeadCta = tapsellNativeadCta;
    this.tapsellNativeadDescription = tapsellNativeadDescription;
    this.tapsellNativeadLogo = tapsellNativeadLogo;
    this.tapsellNativeadRating = tapsellNativeadRating;
    this.tapsellNativeadSponsored = tapsellNativeadSponsored;
    this.tapsellNativeadTitle = tapsellNativeadTitle;
    this.tapsellNativeadVideo = tapsellNativeadVideo;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static AppInstallationVideoAdTemplateBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AppInstallationVideoAdTemplateBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.app_installation_video_ad_template, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AppInstallationVideoAdTemplateBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.rvHeader;
      LinearLayout rvHeader = ViewBindings.findChildViewById(rootView, id);
      if (rvHeader == null) {
        break missingId;
      }

      id = ir.tapsell.plus.R.id.tapsell_nativead_cta;
      Button tapsellNativeadCta = ViewBindings.findChildViewById(rootView, id);
      if (tapsellNativeadCta == null) {
        break missingId;
      }

      id = ir.tapsell.plus.R.id.tapsell_nativead_description;
      TextView tapsellNativeadDescription = ViewBindings.findChildViewById(rootView, id);
      if (tapsellNativeadDescription == null) {
        break missingId;
      }

      id = ir.tapsell.plus.R.id.tapsell_nativead_logo;
      ImageView tapsellNativeadLogo = ViewBindings.findChildViewById(rootView, id);
      if (tapsellNativeadLogo == null) {
        break missingId;
      }

      id = ir.tapsell.plus.R.id.tapsell_nativead_rating;
      RateStarView tapsellNativeadRating = ViewBindings.findChildViewById(rootView, id);
      if (tapsellNativeadRating == null) {
        break missingId;
      }

      id = ir.tapsell.plus.R.id.tapsell_nativead_sponsored;
      TextView tapsellNativeadSponsored = ViewBindings.findChildViewById(rootView, id);
      if (tapsellNativeadSponsored == null) {
        break missingId;
      }

      id = ir.tapsell.plus.R.id.tapsell_nativead_title;
      TextView tapsellNativeadTitle = ViewBindings.findChildViewById(rootView, id);
      if (tapsellNativeadTitle == null) {
        break missingId;
      }

      id = ir.tapsell.plus.R.id.tapsell_nativead_video;
      VideoContainer tapsellNativeadVideo = ViewBindings.findChildViewById(rootView, id);
      if (tapsellNativeadVideo == null) {
        break missingId;
      }

      return new AppInstallationVideoAdTemplateBinding((MaterialCardView) rootView, rvHeader,
          tapsellNativeadCta, tapsellNativeadDescription, tapsellNativeadLogo,
          tapsellNativeadRating, tapsellNativeadSponsored, tapsellNativeadTitle,
          tapsellNativeadVideo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}

که جز کلاس های کتابخانه است

**Comment by MortezaNedaei** [comment]
کد های پیاده سازیتون رو بفرستید. به نظر یه مشکلی مربوط به data binding هست.

**Comment by syedmohdbarzgar** [comment]
کد gradle رو بفرستم

**Comment by syedmohdbarzgar** [comment]
کد های پیاده سازی plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    id("kotlin-kapt")
}

android {
    namespace = "syedmohdbarzgar.ads"
    compileSdk = 34

    buildFeatures {
        //noinspection DataBindingWithoutKapt
        dataBinding = true
        viewBinding = true
        buildConfig = true
    }

    defaultConfig {
        minSdk = 24
        multiDexEnabled = true

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")  }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(project(":netflex"))
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    implementation("ir.tapsell.plus:tapsell-plus-sdk-android:2.2.8")
    implementation("androidx.multidex:multidex:2.0.1")
    // for AdMob
    // The AppId <meta-data> tag is needed
    implementation("com.google.android.gms:play-services-ads:23.5.0")

    //for unityAds
//    implementation("com.unity3d.ads:unity-ads:4.9.2")

    //for chartboost
//    implementation("com.chartboost:chartboost-sdk:8.2.1")
    implementation("com.google.android.gms:play-services-base:18.5.0") {
        exclude(group = "com.android.support")
    }

    implementation("com.google.android.gms:play-services-ads-identifier:18.1.0") {
        exclude(group = "com.android.support")
    }


    //for applovin
//    implementation("com.applovin:applovin-sdk:12.4.0")


    // For Mintegral - NOTE: Add custom repository (explained after this)
//    implementation("com.mbridge.msdk.oversea:mbbanner:16.6.71")
//    implementation("com.mbridge.msdk.oversea:reward:16.6.71")
//    implementation("com.mbridge.msdk.oversea:newinterstitial:16.6.71")
//    implementation("com.mbridge.msdk.oversea:mbbid:16.6.71")

// for TapsellPlus
//    implementation (libs.tapsell.plus.sdk.android)

    // Core SDK and Data dependencies
//    implementation(libs.sdk)

    // for Vast (PreRoll)
    implementation("androidx.media3:media3-ui:1.1.1")
    implementation("androidx.media3:media3-exoplayer:1.1.1")
    implementation("com.google.ads.interactivemedia.v3:interactivemedia:3.33.0")

    // Vast PreRoll (ExoPlayer and Media3)
//    implementation("androidx.media3:media3-ui:1.4.1")
//    implementation("androidx.media3:media3-exoplayer:1.4.1")
//    implementation("com.google.ads.interactivemedia.v3:interactivemedia:3.35.1")

//    implementation("com.huawei.hms:ads-identifier:3.4.34.301")
//    implementation("com.ironsource.sdk:mediationsdk:7.2.0")

//    implementation("com.startapp:inapp-sdk:5.1.0")

    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
}

**Comment by syedmohdbarzgar** [comment]
می توانید بگویید مشکل از کجاست و یک نکته دیگر این خطا زمانی بوجود امد که نسخه اندروید استودیو را ارتقا دادم 


<details><summary>Details</summary>
<p>

Build #AI-242.23339.11.2421.12550806, built on October 24, 2024

</p>
</details> 

 و این مشکل را با کتابخانه تپسل دارد.

**Comment by MortezaNedaei** [comment]
- کد های گریدل به نظر مشکلی ندارن. کد های پیاده‌سازیتون (جایی که تبلیغ رو میسازید و ریکوئست میزنید) رو بفرستید
- ترجیحا از نسخه های استیبل اندروید استودیو استفاده کنید. این نسخه ای که استفاده می‌کنید هم چند تا باگ داره.البته همین اپ سمپل با اندروید استودیو نسخه Meerkat هم تست شده و مشکلی نداره. 
- شما این مشکلات رو در پروژه سمپل هم میبینید؟

**Comment by syedmohdbarzgar** [comment]
من این کد ها رو درون یک کلاس گذاشتم قبل این اندروید استودیو رو بروز کنم یک نسخه از برنامه رو منشر کردم این خطا ها هم وجود نداشت

**Comment by syedmohdbarzgar** [comment]
مشکل را پیدا کردم به خاطر یک فایل هم نام با فایل های کتابخانه تپسل بود
ممنون از پشتیبانی شما

**Comment by MortezaNedaei** [comment]
بسیار عالی. من ایشو رو میبندم پس
